const vocabulary1 = [
  { english: "apple", japanese: "リンゴ", lesson: 0 },
  { english: "April", japanese: "4月", lesson: 0 },
  { english: "book", japanese: "本、書物", lesson: 0 },
  { english: "cat", japanese: "ネコ", lesson: 0 },
  { english: "circle", japanese: "円、輪", lesson: 0 },
  { english: "dog", japanese: "イヌ", lesson: 0 },
  { english: "egg", japanese: "卵", lesson: 0 },
  { english: "Egypt", japanese: "エジプト", lesson: 0 },
  { english: "fish", japanese: "魚", lesson: 0 },
  { english: "glove", japanese: "(野球) グローブ", lesson: 0 },
  { english: "gym", japanese: "体育館", lesson: 0 },
  { english: "horse", japanese: "馬", lesson: 0 },
  { english: "ink", japanese: "インク", lesson: 0 },
  { english: "ice", japanese: "アイス、氷", lesson: 0 },
  { english: "cream", japanese: "クリーム", lesson: 0 },
  { english: "ice cream", japanese: "アイスクリーム", lesson: 0 },
  { english: "jam", japanese: "ジャム", lesson: 0 },
  { english: "king", japanese: "王", lesson: 0 },
  { english: "lunch", japanese: "昼食、(お昼の) 弁当", lesson: 0 },
  { english: "math", japanese: "数学", lesson: 0 },
  { english: "nurse", japanese: "看護師", lesson: 0 },
  { english: "octopus", japanese: "タコ", lesson: 0 },
  { english: "open", japanese: "開く、あける", lesson: 0 },
  { english: "park", japanese: "公園、遊園地", lesson: 0 },
  { english: "queen", japanese: "女王", lesson: 0 },
  { english: "rabbit", japanese: "ウサギ", lesson: 0 },
  { english: "station", japanese: "駅", lesson: 0 },
  { english: "tiger", japanese: "トラ", lesson: 0 },
  { english: "umbrella", japanese: "かさ", lesson: 0 },
  { english: "unicycle", japanese: "一輪車", lesson: 0 },
  { english: "vet", japanese: "獣医", lesson: 0 },
  { english: "weather", japanese: "天気、天候", lesson: 0 },
  { english: "box", japanese: "箱", lesson: 0 },
  { english: "yacht", japanese: "ヨット", lesson: 0 },
  { english: "ZOO", japanese: "動物園", lesson: 0 },
  { english: "subject", japanese: "教科、科目", lesson: 0 },
  { english: "Japanese", japanese: "日本語、国語", lesson: 0 },
  { english: "English", japanese: "英語", lesson: 0 },
  { english: "science", japanese: "理科、自然科学", lesson: 0 },
  { english: "social", japanese: "社会の、社会的な", lesson: 0 },
  { english: "study", japanese: "勉強、研究、学業", lesson: 0 },
  { english: "social studies", japanese: "社会科", lesson: 0 },
  { english: "music", japanese: "音楽", lesson: 0 },
  { english: "P.E.", japanese: "体育", lesson: 0 },
  { english: "art", japanese: "芸術、美術", lesson: 0 },
  { english: "moral", japanese: "道徳的な、道徳の", lesson: 0 },
  { english: "education", japanese: "教育", lesson: 0 },
  { english: "moral education", japanese: "(教科の) 道徳", lesson: 0 },
  { english: "technology", japanese: "科学技術、テクノロジー", lesson: 0 },
  { english: "and", japanese: "〜と〜、〜そして〜", lesson: 0 },
  { english: "home", japanese: "家庭の", lesson: 0 },
  { english: "economics", japanese: "経済学", lesson: 0 },
  { english: "technology and home economics", japanese: "技術家庭科", lesson: 0 },
  { english: "food", japanese: "食べ物", lesson: 0 },
  { english: "beef", japanese: "牛肉", lesson: 0 },
  { english: "chicken", japanese: "とり肉", lesson: 0 },
  { english: "pork", japanese: "豚肉", lesson: 0 },
  { english: "rice", japanese: "米", lesson: 0 },
  { english: "bacon", japanese: "ベーコン", lesson: 0 },
  { english: "cheese", japanese: "チーズ", lesson: 0 },
  { english: "ham", japanese: "ハム", lesson: 0 },
  { english: "nut", japanese: "木の実、ナッツ", lesson: 0 },
  { english: "sausage", japanese: "ソーセージ", lesson: 0 },
  { english: "bread", japanese: "パン、食パン", lesson: 0 },
  { english: "curry", japanese: "カレー料理", lesson: 0 },
  { english: "curry and rice", japanese: "カレーライス", lesson: 0 },
  { english: "French", japanese: "フランスの", lesson: 0 },
  { english: "fry", japanese: "揚げ物、フライ", lesson: 0 },
  { english: "French fries", japanese: "フライドポテト", lesson: 0 },
  { english: "fried", japanese: "油で揚げた", lesson: 0 },
  { english: "fried chicken", japanese: "フライドチキン", lesson: 0 },
  { english: "hamburger", japanese: "ハンバーガー", lesson: 0 },
  { english: "omelet", japanese: "オムレツ", lesson: 0 },
  { english: "pizza", japanese: "ピザ", lesson: 0 },
  { english: "ball", japanese: "ボール、球、玉", lesson: 0 },
  { english: "rice ball", japanese: "おにぎり", lesson: 0 },
  { english: "salad", japanese: "サラダ", lesson: 0 },
  { english: "sandwich", japanese: "サンドイッチ", lesson: 0 },
  { english: "spaghetti", japanese: "スパゲッティ", lesson: 0 },
  { english: "steak", japanese: "ステーキ", lesson: 0 },
  { english: "corn", japanese: "トウモロコシ", lesson: 0 },
  { english: "soup", japanese: "スープ", lesson: 0 },
  { english: "grilled", japanese: "グリルで焼いた", lesson: 0 },
  { english: "grilled fish", japanese: "焼き魚", lesson: 0 },
  { english: "hot", japanese: "熱い、暑い", lesson: 0 },
  { english: "hot dog", japanese: "ホットドッグ", lesson: 0 },
  { english: "noodle", japanese: "麺類", lesson: 0 },
  { english: "sushi", japanese: "寿司", lesson: 0 },
  { english: "fruit", japanese: "果物、木の実", lesson: 0 },
  { english: "vegetable", japanese: "野菜", lesson: 0 },
  { english: "banana", japanese: "バナナ", lesson: 0 },
  { english: "carrot", japanese: "ニンジン", lesson: 0 },
  { english: "cherry", japanese: "サクランボ", lesson: 0 },
  { english: "grape", japanese: "ブドウ", lesson: 0 },
  { english: "lemon", japanese: "レモン", lesson: 0 },
  { english: "orange", japanese: "オレンジ", lesson: 0 },
  { english: "peach", japanese: "モモ", lesson: 0 },
  { english: "pineapple", japanese: "パイナップル", lesson: 0 },
  { english: "potato", japanese: "ジャガイモ", lesson: 0 },
  { english: "tomato", japanese: "トマト", lesson: 0 },
  { english: "watermelon", japanese: "スイカ", lesson: 0 },
  { english: "cabbage", japanese: "キャベツ", lesson: 0 },
  { english: "cucumber", japanese: "キュウリ", lesson: 0 },
  { english: "green", japanese: "緑色の", lesson: 0 },
  { english: "pepper", japanese: "コショウ、トウガラシの実", lesson: 0 },
  { english: "green pepper", japanese: "ピーマン", lesson: 0 },
  { english: "kiwi", japanese: "キウイ", lesson: 0 },
  { english: "kiwi fruit", japanese: "キウイフルーツ", lesson: 0 },
  { english: "lettuce", japanese: "レタス", lesson: 0 },
  { english: "melon", japanese: "メロン", lesson: 0 },
  { english: "mushroom", japanese: "キノコ", lesson: 0 },
  { english: "onion", japanese: "タマネギ", lesson: 0 },
  { english: "strawberry", japanese: "イチゴ", lesson: 0 },
  { english: "dessert", japanese: "デザート", lesson: 0 },
  { english: "drink", japanese: "飲みもの", lesson: 0 },
  { english: "cake", japanese: "ケーキ", lesson: 0 },
  { english: "chocolate", japanese: "チョコレート", lesson: 0 },
  { english: "pie", japanese: "パイ", lesson: 0 },
  { english: "popcorn", japanese: "ポップコーン", lesson: 0 },
  { english: "pudding", japanese: "プリン", lesson: 0 },
  { english: "donut", japanese: "ドーナツ", lesson: 0 },
  { english: "pancake", japanese: "パンケーキ", lesson: 0 },
  { english: "parfait", japanese: "パフェ", lesson: 0 },
  { english: "shaved ice", japanese: "かき氷", lesson: 0 },
  { english: "snack", japanese: "スナック菓子、軽食", lesson: 0 },
  { english: "snack food", japanese: "スナック菓子", lesson: 0 },
  { english: "yogurt", japanese: "ヨーグルト", lesson: 0 },
  { english: "coffee", japanese: "コーヒー", lesson: 0 },
  { english: "tea", japanese: "茶、(特に) 紅茶", lesson: 0 },
  { english: "green tea", japanese: "緑茶", lesson: 0 },
  { english: "juice", japanese: "ジュース", lesson: 0 },
  { english: "milk", japanese: "牛乳", lesson: 0 },
  { english: "water", japanese: "水", lesson: 0 },
  { english: "sport", japanese: "スポーツ", lesson: 0 },
  { english: "badminton", japanese: "バドミントン", lesson: 0 },
  { english: "baseball", japanese: "野球", lesson: 0 },
  { english: "basketball", japanese: "バスケットボール", lesson: 0 },
  { english: "judo", japanese: "柔道", lesson: 0 },
  { english: "rugby", japanese: "ラグビー", lesson: 0 },
  { english: "skateboarding", japanese: "スケートボード(に乗ること)", lesson: 0 },
  { english: "skiing", japanese: "スキー(ですべること)", lesson: 0 },
  { english: "soccer", japanese: "サッカー", lesson: 0 },
  { english: "table", japanese: "テーブル、食卓", lesson: 0 },
  { english: "tennis", japanese: "テニス", lesson: 0 },
  { english: "table tennis", japanese: "卓球", lesson: 0 },
  { english: "volleyball", japanese: "バレーボール", lesson: 0 },
  { english: "wheelchair", japanese: "車いす", lesson: 0 },
  { english: "archery", japanese: "アーチェリー、弓道", lesson: 0 },
  { english: "gymnastics", japanese: "体操", lesson: 0 },
  { english: "skating", japanese: "スケート(すること)", lesson: 0 },
  { english: "softball", japanese: "ソフトボール", lesson: 0 },
  { english: "swimming", japanese: "水泳", lesson: 0 },
  { english: "track", japanese: "走路、トラック", lesson: 0 },
  { english: "field", japanese: "(陸上競技場の) フィールド", lesson: 0 },
  { english: "track and field", japanese: "陸上競技", lesson: 0 },
  { english: "animal", japanese: "動物", lesson: 0 },
  { english: "bear", japanese: "クマ", lesson: 0 },
  { english: "bird", japanese: "鳥", lesson: 0 },
  { english: "fox", japanese: "キツネ", lesson: 0 },
  { english: "lion", japanese: "ライオン", lesson: 0 },
  { english: "monkey", japanese: "サル", lesson: 0 },
  { english: "panda", japanese: "パンダ", lesson: 0 },
  { english: "pig", japanese: "ブタ", lesson: 0 },
  { english: "zebra", japanese: "シマウマ", lesson: 0 },
  { english: "cow", japanese: "雌牛、乳牛、 ウシ", lesson: 0 },
  { english: "dolphin", japanese: "イルカ", lesson: 0 },
  { english: "elephant", japanese: "ゾウ", lesson: 0 },
  { english: "gorilla", japanese: "ゴリラ", lesson: 0 },
  { english: "koala", japanese: "コアラ", lesson: 0 },
  { english: "mouse", japanese: "ネズミ", lesson: 0 },
  { english: "penguin", japanese: "ペンギン", lesson: 0 },
  { english: "snake", japanese: "ヘビ", lesson: 0 },
  { english: "shape", japanese: "形、姿", lesson: 0 },
  { english: "heart", japanese: "ハート型", lesson: 0 },
  { english: "rectangle", japanese: "長方形", lesson: 0 },
  { english: "square", japanese: "正方形、四角形", lesson: 0 },
  { english: "star", japanese: "星形のもの、星印", lesson: 0 },
  { english: "triangle", japanese: "三角形", lesson: 0 },
  { english: "color", japanese: "色、色彩", lesson: 0 },
  { english: "black", japanese: "黒色", lesson: 0 },
  { english: "blue", japanese: "青色", lesson: 0 },
  { english: "brown", japanese: "茶色(の)、褐色(の)", lesson: 0 },
  { english: "green", japanese: "緑色", lesson: 0 },
  { english: "orange", japanese: "オレンジ色", lesson: 0 },
  { english: "pink", japanese: "ピンク色(の)", lesson: 0 },
  { english: "purple", japanese: "紫色(の)", lesson: 0 },
  { english: "red", japanese: "赤色(の)", lesson: 0 },
  { english: "white", japanese: "白色", lesson: 0 },
  { english: "yellow", japanese: "黄色(の)", lesson: 0 },
  { english: "big", japanese: "大きい", lesson: 0 },
  { english: "small", japanese: "小さい、 (面積が) 狭い", lesson: 0 },
  { english: "long", japanese: "長い", lesson: 0 },
  { english: "short", japanese: "短い", lesson: 0 },
  { english: "old", japanese: "古い、 昔の、", lesson: 0 },
  { english: "new", japanese: "新しい、 目新しい、見慣れない", lesson: 0 },
  { english: "hard", japanese: "かたい", lesson: 0 },
  { english: "soft", japanese: "やわらかい", lesson: 0 },
  { english: "fast", japanese: "速い、すばやい", lesson: 0 },
  { english: "slow", japanese: "遅い、 ゆっくりとした", lesson: 0 },
  { english: "beautiful", japanese: "美しい、きれいな", lesson: 0 },
  { english: "nice", japanese: "すてきな、すばらしい、 おいしい", lesson: 0 },
  { english: "cool", japanese: "かっこいい、すばらしい、おしゃれな", lesson: 0 },
  { english: "great", japanese: "すてきな、すばらしい", lesson: 0 },
  { english: "really", japanese: "ほんと、へえー、そうなの", lesson: 0 },
  { english: "cute", japanese: "かわいい", lesson: 0 },
  { english: "famous", japanese: "有名な", lesson: 0 },
  { english: "friendly", japanese: "親しみのある、 親切な、人なつこい", lesson: 0 },
  { english: "kind", japanese: "親切な、やさしい", lesson: 0 },
  { english: "strong", japanese: "強い", lesson: 0 },
  { english: "brave", japanese: "勇敢な", lesson: 0 },
  { english: "funny", japanese: "こっけいな、おかしい、おもしろい", lesson: 0 },
  { english: "smart", japanese: "頭のよい、 利口な", lesson: 0 },
  { english: "salty", japanese: "塩けのある、塩からい", lesson: 0 },
  { english: "sour", japanese: "すっぱい", lesson: 0 },
  { english: "spicy", japanese: "香辛料のきいた", lesson: 0 },
  { english: "cold", japanese: "冷たい、 寒い", lesson: 0 },
  { english: "delicious", japanese: "(とても) おいしい", lesson: 0 },
  { english: "bitter", japanese: "にがい", lesson: 0 },
  { english: "fresh", japanese: "新しい、新鮮な", lesson: 0 },
  { english: "sweet", japanese: "甘い", lesson: 0 },
  { english: "exciting", japanese: "興奮させる、とてもおもしろい", lesson: 0 },
  { english: "fine", japanese: "健康な[で]、元気な", lesson: 0 },
  { english: "fun", japanese: "おもしろいこと、楽しさ", lesson: 0 },
  { english: "good", japanese: "よい、すぐれた", lesson: 0 },
  { english: "interesting", japanese: "おもしろい、興味深い", lesson: 0 },
  { english: "angry", japanese: "怒った、腹をたてた", lesson: 0 },
  { english: "happy", japanese: "幸せな、うれしい、楽しい", lesson: 0 },
  { english: "hungry", japanese: "空腹の", lesson: 0 },
  { english: "sad", japanese: "悲しい", lesson: 0 },
  { english: "sleepy", japanese: "眠い、眠そうな", lesson: 0 },
  { english: "thirsty", japanese: "のどがかわいて", lesson: 0 },
  { english: "season", japanese: "季節", lesson: 0 },
  { english: "always", japanese: "いつも、常に", lesson: 0 },
  { english: "usually", japanese: "たいてい、ふつう、いつも(は)", lesson: 0 },
  { english: "sometimes", japanese: "ときどき、時には", lesson: 0 },
  { english: "never", japanese: "決して…ない", lesson: 0 },
  { english: "morning", japanese: "朝、 午前", lesson: 0 },
  { english: "afternoon", japanese: "午後", lesson: 0 },
  { english: "evening", japanese: "夕方、晩", lesson: 0 },
  { english: "night", japanese: "夜、 晩、夕方、 夜中", lesson: 0 },
  { english: "spring", japanese: "春", lesson: 0 },
  { english: "summer", japanese: "夏", lesson: 0 },
  { english: "autumn", japanese: "秋", lesson: 0 },
  { english: "fall", japanese: "秋 (主にアメリカ英語)", lesson: 0 },
  { english: "winter", japanese: "冬", lesson: 0 },
  { english: "get", japanese: "(ある状態)になる", lesson: 0 },
  { english: "up", japanese: "起きて、目が覚めて", lesson: 0 },
  { english: "get up", japanese: "起きる", lesson: 0 },
  { english: "wash", japanese: "洗う", lesson: 0 },
  { english: "my", japanese: "私の", lesson: 0 },
  { english: "face", japanese: "顔、 表情", lesson: 0 },
  { english: "brush", japanese: "ブラシをかける、ブラシでみがく", lesson: 0 },
  { english: "tooth", japanese: "歯", lesson: 0 },
  { english: "teeth", japanese: "歯 (toothの複数形)", lesson: 0 },
  { english: "eat", japanese: "食べる、 食事をする", lesson: 0 },
  { english: "breakfast", japanese: "朝食、朝ご飯", lesson: 0 },
  { english: "take", japanese: "(手に取って) [･･･に]持って行く、連れて行く", lesson: 0 },
  { english: "out", japanese: "外へ、外に", lesson: 0 },
  { english: "take out", japanese: "取り出す、出す", lesson: 0 },
  { english: "garbage", japanese: "ごみ", lesson: 0 },
  { english: "leave", japanese: "去る、離れる", lesson: 0 },
  { english: "home", japanese: "家庭、家", lesson: 0 },
  { english: "go", japanese: "行く、出発する", lesson: 0 },
  { english: "to", japanese: "へ、…に", lesson: 0 },
  { english: "school", japanese: "学校", lesson: 0 },
  { english: "study", japanese: "勉強する、研究する", lesson: 0 },
  { english: "clean", japanese: "きれいにする、そうじする", lesson: 0 },
  { english: "the", japanese: "その、あの", lesson: 0 },
  { english: "classroom", japanese: "教室", lesson: 0 },
  { english: "practice", japanese: "練習する", lesson: 0 },
  { english: "home", japanese: "家が[へ]、家に[へ]", lesson: 0 },
  { english: "do", japanese: "する、行う、 行動する", lesson: 0 },
  { english: "homework", japanese: "宿題", lesson: 0 },
  { english: "do one's homework", japanese: "宿題をする", lesson: 0 },
  { english: "walk", japanese: "(犬などを) 散歩させる", lesson: 0 },
  { english: "dinner", japanese: "ディナー、夕食", lesson: 0 },
  { english: "dish", japanese: "皿、 食器類", lesson: 0 },
  { english: "take", japanese: "(ある行動を)する、とる", lesson: 0 },
  { english: "a", japanese: "1つの、1人の、 ある(1つ[1人]の)", lesson: 0 },
  { english: "bath", japanese: "風呂そう、入浴", lesson: 0 },
  { english: "take a bath", japanese: "入浴する", lesson: 0 },
  { english: "bed", japanese: "ベッド、寝床、寝台", lesson: 0 },
  { english: "go to bed", japanese: "寝る", lesson: 0 },
  { english: "cook", japanese: "(熱を使って) 料理する", lesson: 0 },
  { english: "draw", japanese: "(絵などを) かく", lesson: 0 },
  { english: "picture", japanese: "絵、絵画", lesson: 0 },
  { english: "drink", japanese: "飲む", lesson: 0 },
  { english: "library", japanese: "図書館、書室", lesson: 0 },
  { english: "listen", japanese: "(じっと) 聞く、耳を傾ける", lesson: 0 },
  { english: "to", japanese: "〜に、〜に対して", lesson: 0 },
  { english: "listen to", japanese: "〜を聞く", lesson: 0 },
  { english: "make", japanese: "作る、こしらえる", lesson: 0 },
  { english: "play", japanese: "演奏する", lesson: 0 },
  { english: "guitar", japanese: "ギター", lesson: 0 },
  { english: "read", japanese: "読む、読書する", lesson: 0 },
  { english: "ride", japanese: "乗る、乗って行く", lesson: 0 },
  { english: "bike", japanese: "自転車", lesson: 0 },
  { english: "run", japanese: "走る、走って行く", lesson: 0 },
  { english: "see", japanese: "見る、〜が見える", lesson: 0 },
  { english: "movie", japanese: "映画", lesson: 0 },
  { english: "sing", japanese: "歌う", lesson: 0 },
  { english: "swim", japanese: "泳ぐ", lesson: 0 },
  { english: "talk", japanese: "話す、しゃべる、話をする", lesson: 0 },
  { english: "with", japanese: "〜と、〜に(対して)", lesson: 0 },
  { english: "friend", japanese: "友人、友だち", lesson: 0 },
  { english: "use", japanese: "使う、使用する、利用する", lesson: 0 },
  { english: "computer", japanese: "コンピュータ", lesson: 0 },
  { english: "watch", japanese: "注意して見る、じっと見る", lesson: 0 },
  { english: "TV", japanese: "テレビ", lesson: 0 },
  { english: "write", japanese: "書く", lesson: 0 },
  { english: "letter", japanese: "手紙", lesson: 0 },
  { english: "play", japanese: "(スポーツ・ゲームなどを) する", lesson: 0 },
  { english: "card", japanese: "トランプの札、 トランプ遊び", lesson: 0 },
  { english: "jump", japanese: "とぶ、はねる", lesson: 0 },
  { english: "rope", japanese: "(太い) 綱、なわ", lesson: 0 },
  { english: "fun", japanese: "楽しい、おもしろい", lesson: 0 },
  { english: "quiz", japanese: "クイズ", lesson: 0 },
  { english: "enjoy", japanese: "(〜を) 楽しむ、 味わう", lesson: 0 },
  { english: "camping", japanese: "キャンプすること", lesson: 0 },
  { english: "fishing", japanese: "魚釣り", lesson: 0 },
  { english: "hiking", japanese: "ハイキング", lesson: 0 },
  { english: "jogging", japanese: "ジョギング", lesson: 0 },
  { english: "shopping", japanese: "買い物", lesson: 0 },
  { english: "surfing", japanese: "サーフィン", lesson: 0 },
  { english: "club", japanese: "クラブ、部", lesson: 0 },
  { english: "lesson", japanese: "(学校の) 授業、習いごと", lesson: 0 },
  { english: "brass", japanese: "金管楽器", lesson: 0 },
  { english: "band", japanese: "バンド、楽団", lesson: 0 },
  { english: "brass band", japanese: "ブラスバンド、吹奏楽団", lesson: 0 },
  { english: "calligraphy", japanese: "書道", lesson: 0 },
  { english: "chorus", japanese: "合唱、コーラス", lesson: 0 },
  { english: "cooking", japanese: "料理", lesson: 0 },
  { english: "dance", japanese: "踊り、ダンス", lesson: 0 },
  { english: "drama", japanese: "ドラマ、劇", lesson: 0 },
  { english: "English", japanese: "英語の", lesson: 0 },
  { english: "newspaper", japanese: "新聞、新聞紙", lesson: 0 },
  { english: "drum", japanese: "太鼓、ドラム", lesson: 0 },
  { english: "piano", japanese: "ピアノ", lesson: 0 },
  { english: "recorder", japanese: "リコーダー", lesson: 0 },
  { english: "trumpet", japanese: "トランペット", lesson: 0 },
  { english: "violin", japanese: "バイオリン", lesson: 0 },
  { english: "Sunday", japanese: "日曜日", lesson: 0 },
  { english: "Monday", japanese: "月曜日", lesson: 0 },
  { english: "Tuesday", japanese: "火曜日", lesson: 0 },
  { english: "Wednesday", japanese: "水曜日", lesson: 0 },
  { english: "Thursday", japanese: "木曜日", lesson: 0 },
  { english: "Friday", japanese: "金曜日", lesson: 0 },
  { english: "Saturday", japanese: "土曜日", lesson: 0 },
  { english: "time", japanese: "時刻、時間", lesson: 0 },
  { english: "one", japanese: "1、 1つ、1人", lesson: 0 },
  { english: "two", japanese: "2(の)", lesson: 0 },
  { english: "three", japanese: "3(の)", lesson: 0 },
  { english: "four", japanese: "4(の)", lesson: 0 },
  { english: "five", japanese: "5(の)", lesson: 0 },
  { english: "six", japanese: "6(の)", lesson: 0 },
  { english: "seven", japanese: "7(の)", lesson: 0 },
  { english: "eight", japanese: "8(の)", lesson: 0 },
  { english: "nine", japanese: "9(の)", lesson: 0 },
  { english: "ten", japanese: "10(の)", lesson: 0 },
  { english: "eleven", japanese: "11(の)", lesson: 0 },
  { english: "twelve", japanese: "12(の)", lesson: 0 },
  { english: "fifteen", japanese: "15(の)", lesson: 0 },
  { english: "twenty", japanese: "20(の)", lesson: 0 },
  { english: "thirty", japanese: "30(の)", lesson: 0 },
  { english: "forty", japanese: "40(の)", lesson: 0 },
  { english: "fifty", japanese: "50(の)", lesson: 0 },
  { english: "a.m.", japanese: "午前", lesson: 0 },
  { english: "p.m.", japanese: "午後", lesson: 0 },
  { english: "beach", japanese: "浜、砂浜、浜辺", lesson: 0 },
  { english: "flower", japanese: "花", lesson: 0 },
  { english: "lake", japanese: "湖、湖水", lesson: 0 },
  { english: "mountain", japanese: "山", lesson: 0 },
  { english: "river", japanese: "川、河", lesson: 0 },
  { english: "sea", japanese: "海、 海の", lesson: 0 },
  { english: "country", japanese: "国、国土", lesson: 0 },
  { english: "Australia", japanese: "オーストラリア", lesson: 0 },
  { english: "Brazil", japanese: "ブラジル", lesson: 0 },
  { english: "Canada", japanese: "カナダ", lesson: 0 },
  { english: "China", japanese: "中国", lesson: 0 },
  { english: "France", japanese: "フランス", lesson: 0 },
  { english: "India", japanese: "インド", lesson: 0 },
  { english: "Japan", japanese: "日本", lesson: 0 },
  { english: "south", japanese: "南(の)", lesson: 0 },
  { english: "Korea", japanese: "韓国・朝鮮", lesson: 0 },
  { english: "South Korea", japanese: "韓国", lesson: 0 },
  { english: "Spain", japanese: "スペイン", lesson: 0 },
  { english: "the U.K.", japanese: "イギリス", lesson: 0 },
  { english: "the U.S.A.", japanese: "アメリカ合衆国", lesson: 0 },
  { english: "Germany", japanese: "ドイツ", lesson: 0 },
  { english: "Ghana", japanese: "ガーナ", lesson: 0 },
  { english: "Italy", japanese: "イタリア", lesson: 0 },
  { english: "Kenya", japanese: "ケニア", lesson: 0 },
  { english: "Peru", japanese: "ペルー", lesson: 0 },
  { english: "Russia", japanese: "ロシア連邦", lesson: 0 },
  { english: "Singapore", japanese: "シンガポール", lesson: 0 },
  { english: "Thailand", japanese: "タイ", lesson: 0 },
  { english: "Turkey", japanese: "トルコ", lesson: 0 },
  { english: "bag", japanese: "袋、 カバン、バッグ", lesson: 0 },
  { english: "clock", japanese: "時計 (置き時計・掛け時計)", lesson: 0 },
  { english: "hat", japanese: "(ふちのある) 帽子", lesson: 0 },
  { english: "notebook", japanese: "ノート", lesson: 0 },
  { english: "pen", japanese: "ペン", lesson: 0 },
  { english: "pencil", japanese: "鉛筆", lesson: 0 },
  { english: "case", japanese: "ケース、箱、〜入れ", lesson: 0 },
  { english: "pencil case", japanese: "筆箱", lesson: 0 },
  { english: "ruler", japanese: "ものさし、定規", lesson: 0 },
  { english: "scissors", japanese: "はさみ", lesson: 0 },
  { english: "watch", japanese: "(携帯用の) 腕時計、時計", lesson: 0 },
  { english: "cap", japanese: "(ふちのない) 帽子", lesson: 0 },
  { english: "cup", japanese: "茶わん、カップ", lesson: 0 },
  { english: "eraser", japanese: "消しゴム", lesson: 0 },
  { english: "pants", japanese: "ズボン", lesson: 0 },
  { english: "shoe", japanese: "靴", lesson: 0 },
  { english: "T-shirt", japanese: "Tシャツ", lesson: 0 },
  { english: "amusement", japanese: "楽しみ、娯楽", lesson: 0 },
  { english: "amusement park", japanese: "遊園地", lesson: 0 },
  { english: "aquarium", japanese: "水族館", lesson: 0 },
  { english: "castle", japanese: "城", lesson: 0 },
  { english: "hospital", japanese: "病院", lesson: 0 },
  { english: "house", japanese: "家、住宅", lesson: 0 },
  { english: "museum", japanese: "博物館、 美術館", lesson: 0 },
  { english: "restaurant", japanese: "レストラン", lesson: 0 },
  { english: "shrine", japanese: "神社、神宮", lesson: 0 },
  { english: "stadium", japanese: "競技場、スタジアム", lesson: 0 },
  { english: "temple", japanese: "神殿、 寺院", lesson: 0 },
  { english: "elementary", japanese: "初歩的な、初級の", lesson: 0 },
  { english: "elementary school", japanese: "小学校", lesson: 0 },
  { english: "junior", japanese: "年下の、年少の、 後輩の", lesson: 0 },
  { english: "high", japanese: "高い", lesson: 0 },
  { english: "junior high school", japanese: "中学校", lesson: 0 },
  { english: "about", japanese: "〜に関して（の）、だいたい、約〜、ほぼ", lesson: 1 },
  { english: "me", japanese: "私を、私に、私", lesson: 1 },
  { english: "Kate", japanese: "ケイト", lesson: 1 },
  { english: "Jing", japanese: "ヂン", lesson: 1 },
  { english: "Mark", japanese: "マーク", lesson: 1 },
  { english: "Dinu", japanese: "ディヌー", lesson: 1 },
  { english: "Ms.", japanese: "〜さん、〜先生", lesson: 1 },
  { english: "Brown", japanese: "ブラウン（人の姓）", lesson: 1 },
  { english: "uh-huh", japanese: "うんうん、なるほど", lesson: 1 },
  { english: "I", japanese: "私は、私が", lesson: 1 },
  { english: "see", japanese: "わかる、理解する", lesson: 1 },
  { english: "I see.", japanese: "わかりました", lesson: 1 },
  { english: "too", japanese: "（〜も）また", lesson: 1 },
  { english: "Me, too.", japanese: "私も", lesson: 1 },
  { english: "am", japanese: "〜てある", lesson: 1 },
  { english: "like", japanese: "〜を好む、〜が好きである", lesson: 1 },
  { english: "I'm", japanese: "I am の短縮形", lesson: 1 },
  { english: "hi", japanese: "こんにちは、やあ", lesson: 1 },
  { english: "often", japanese: "たびたび、よく", lesson: 1 },
  { english: "game", japanese: "試合、競技", lesson: 1 },
  { english: "on", japanese: "〜で、〜によって", lesson: 1 },
  { english: "good", japanese: "上手な、うまい", lesson: 1 },
  { english: "at", japanese: "〜の点において、〜に関して（は）", lesson: 1 },
  { english: "be good at…", japanese: "〜が上手である", lesson: 1 },
  { english: "in", japanese: "〜（の状態）で、〜になって", lesson: 1 },
  { english: "to", japanese: "〜して", lesson: 1 },
  { english: "meet", japanese: "会う、出会う", lesson: 1 },
  { english: "you", japanese: "あなたを、あなたに、あなたたちを", lesson: 1 },
  { english: "are", japanese: "〜である", lesson: 1 },
  { english: "fan", japanese: "ファン", lesson: 1 },
  { english: "yes", japanese: "はい、ええ、そうです", lesson: 1 },
  { english: "no", japanese: "いいえ、いや", lesson: 1 },
  { english: "not", japanese: "〜ない、〜しない", lesson: 1 },
  { english: "do", japanese: "〜しますか", lesson: 1 },
  { english: "every", japanese: "ごとに", lesson: 1 },
  { english: "day", japanese: "日、1日", lesson: 1 },
  { english: "every day", japanese: "毎日", lesson: 1 },
  { english: "do", japanese: "〜する", lesson: 1 },
  { english: "don't", japanese: "〜しない", lesson: 1 },
  { english: "are", japanese: "〜にいる、〜にある", lesson: 1 },
  { english: "in", japanese: "〜に従事して", lesson: 1 },
  { english: "at", japanese: "〜に、〜で", lesson: 1 },
  { english: "at school", japanese: "学校で", lesson: 1 },
  { english: "take", japanese: "（授業・試験などを）受ける", lesson: 1 },
  { english: "after", japanese: "〜のあとに", lesson: 1 },
  { english: "after school", japanese: "放課後", lesson: 1 },
  { english: "dance", japanese: "踊る、ダンスをする", lesson: 1 },
  { english: "hip-hop", japanese: "ヒップホップ", lesson: 1 },
  { english: "dancer", japanese: "ダンサー", lesson: 1 },
  { english: "on", japanese: "〜（日）に", lesson: 1 },
  { english: "rock", japanese: "ロック（音楽）", lesson: 1 },
  { english: "J-pop", japanese: "日本のポピュラー音楽", lesson: 1 },
  { english: "action", japanese: "動き、演技、動作", lesson: 1 },
  { english: "anime", japanese: "アニメ", lesson: 1 },
  { english: "really", japanese: "本当に、実際に", lesson: 1 },
  { english: "manga", japanese: "マンガ（本）", lesson: 1 },
  { english: "what", japanese: "何を", lesson: 1 },
  { english: "weekend", japanese: "週末", lesson: 1 },
  { english: "at home", japanese: "うちに、うちで", lesson: 1 },
  { english: "what", japanese: "何の、何という、どんな", lesson: 1 },
  { english: "take", japanese: "（写真を）とる、書き取る", lesson: 1 },
  { english: "picture", japanese: "写真", lesson: 1 },
  { english: "take a picture", japanese: "写真を撮る", lesson: 1 },
  { english: "of", japanese: "〜のことを、〜について（の）", lesson: 1 },
  { english: "iguana", japanese: "イグアナ", lesson: 1 },
  { english: "look", japanese: "見る", lesson: 1 },
  { english: "at", japanese: "〜に向かって、〜をめがけて", lesson: 1 },
  { english: "look at…", japanese: "〜を見る", lesson: 1 },
  { english: "this", japanese: "この、こちらの", lesson: 1 },
  { english: "pet", japanese: "ペット", lesson: 1 },
  { english: "have", japanese: "持っている、所有している", lesson: 1 },
  { english: "an", japanese: "1つの、1人の", lesson: 1 },
  { english: "love", japanese: "愛する、大好きである", lesson: 1 },
  { english: "Winnie-the-Pooh", japanese: "『クマのプーさん』", lesson: 1 },
  { english: "Peter Pan", japanese: "『ピーター・パン』", lesson: 1 },
  { english: "Peter Rabbit", japanese: "『ピーターラビットのおはなし』", lesson: 1 },
  { english: "flavor", japanese: "味、風味", lesson: 1 },
  { english: "many", japanese: "多くの、たくさんの", lesson: 1 },
  { english: "about", japanese: "だいたい、約〜、ほぼ", lesson: 1 },
  { english: "tablet", japanese: "タブレット", lesson: 1 },
  { english: "how", japanese: "どれくらい、どれほど", lesson: 1 },
  { english: "number", japanese: "数", lesson: 1 },
  { english: "zero", japanese: "ゼロ", lesson: 1 },
  { english: "thirteen", japanese: "13（の）", lesson: 1 },
  { english: "fourteen", japanese: "14（の）", lesson: 1 },
  { english: "sixteen", japanese: "16（の）", lesson: 1 },
  { english: "seventeen", japanese: "17（の）", lesson: 1 },
  { english: "eighteen", japanese: "18（の）", lesson: 1 },
  { english: "nineteen", japanese: "19（の）", lesson: 1 },
  { english: "sixty", japanese: "60（の）", lesson: 1 },
  { english: "seventy", japanese: "70（の）", lesson: 1 },
  { english: "eighty", japanese: "80（の）", lesson: 1 },
  { english: "ninety", japanese: "90（の）", lesson: 1 },
  { english: "one", japanese: "1つの、1人の", lesson: 1 },
  { english: "hundred", japanese: "100（の）", lesson: 1 },
  { english: "thousand", japanese: "1,000（の）", lesson: 1 },
  { english: "hero", japanese: "英雄、ヒーロー", lesson: 2 },
  { english: "Li", japanese: "人の姓", lesson: 2 },
  { english: "Ming", japanese: "男性の名前", lesson: 2 },
  { english: "firefighter", japanese: "消防士", lesson: 2 },
  { english: "fast", japanese: "(速度が)速く", lesson: 2 },
  { english: "smile", japanese: "ほほえみ; 微笑", lesson: 2 },
  { english: "she", japanese: "彼女は、彼女が", lesson: 2 },
  { english: "can", japanese: "･･･することができる", lesson: 2 },
  { english: "skateboard", japanese: "スケートボードをする", lesson: 2 },
  { english: "very", japanese: "とても、非常に、たいへん", lesson: 2 },
  { english: "well", japanese: "うまく、上手に", lesson: 2 },
  { english: "he", japanese: "彼は、彼が", lesson: 2 },
  { english: "is", japanese: "(･･･で)ある", lesson: 2 },
  { english: "popular", japanese: "人気のある; 流行の", lesson: 2 },
  { english: "singer", japanese: "歌手", lesson: 2 },
  { english: "in", japanese: "･･･(の中)に、･･･(の中)で[の]; (乗り物)に乗って、･･･で; ･･･の中で[を]; ･･･の中へ[に]", lesson: 2 },
  { english: "her", japanese: "彼女の", lesson: 2 },
  { english: "powerful", japanese: "力の強い、強力な", lesson: 2 },
  { english: "voice", japanese: "声", lesson: 2 },
  { english: "favorite", japanese: "お気に入りの、大好きな", lesson: 2 },
  { english: "song", japanese: "歌", lesson: 2 },
  { english: "it", japanese: "それは、それが", lesson: 2 },
  { english: "love", japanese: "愛、愛情", lesson: 2 },
  { english: "please", japanese: "どうぞ、すみませんが; お願いします", lesson: 2 },
  { english: "she's", japanese: "she is の短縮形", lesson: 2 },
  { english: "it's", japanese: "it is の短縮形", lesson: 2 },
  { english: "cannot", japanese: "canの否定形", lesson: 2 },
  { english: "can't", japanese: "cannotの短縮形", lesson: 2 },
  { english: "Can you…?", japanese: "してもらえませんか、･･･してくれませんか", lesson: 2 },
  { english: "teach", japanese: "(人に知識・技術・教科などを)教える", lesson: 2 },
  { english: "it", japanese: "それを、それに、それ", lesson: 2 },
  { english: "sure", japanese: "もちろん、はい、いいですとも", lesson: 2 },
  { english: "piece", japanese: "(チェス・将棋などの)駒", lesson: 2 },
  { english: "the", japanese: "日本語には訳さないことが多い", lesson: 2 },
  { english: "on", japanese: "･･･の上に、･･･の上の; ･･･の表面に[の]; ･･･に(乗って)", lesson: 2 },
  { english: "move", japanese: "動かす、移動させる; 動く; 移動する", lesson: 2 },
  { english: "space", japanese: "場所、空間", lesson: 2 },
  { english: "forward", japanese: "前へ、前方へ", lesson: 2 },
  { english: "uncle", japanese: "おじ", lesson: 2 },
  { english: "language", japanese: "言語、(ある国・民族の)ことば、国語", lesson: 2 },
  { english: "his", japanese: "彼の", lesson: 2 },
  { english: "speak", japanese: "(ある言語を)話す、話す能力がある", lesson: 2 },
  { english: "Chinese", japanese: "中国語", lesson: 2 },
  { english: "he's", japanese: "he is の短縮形", lesson: 2 },
  { english: "when", japanese: "いつ", lesson: 2 },
  { english: "your", japanese: "あなたの; あなたたちの", lesson: 2 },
  { english: "birthday", japanese: "誕生日;〔形容詞的に〕誕生日の", lesson: 2 },
  { english: "month", japanese: "月; ひと月 (間)", lesson: 2 },
  { english: "January", japanese: "1月", lesson: 2 },
  { english: "February", japanese: "2月", lesson: 2 },
  { english: "March", japanese: "3月", lesson: 2 },
  { english: "April", japanese: "4月", lesson: 2 },
  { english: "May", japanese: "5月", lesson: 2 },
  { english: "June", japanese: "6月", lesson: 2 },
  { english: "July", japanese: "7月", lesson: 2 },
  { english: "August", japanese: "8月", lesson: 2 },
  { english: "September", japanese: "9月", lesson: 2 },
  { english: "October", japanese: "10月", lesson: 2 },
  { english: "November", japanese: "11月", lesson: 2 },
  { english: "December", japanese: "12月", lesson: 2 },
  { english: "date", japanese: "日付; 日、(年)月日", lesson: 2 },
  { english: "first", japanese: "1番目(の); 最初(の)", lesson: 2 },
  { english: "second", japanese: "2番目(の)", lesson: 2 },
  { english: "third", japanese: "3番目(の)", lesson: 2 },
  { english: "fourth", japanese: "4番目(の)", lesson: 2 },
  { english: "fifth", japanese: "5番目(の)", lesson: 2 },
  { english: "sixth", japanese: "6番目(の)", lesson: 2 },
  { english: "seventh", japanese: "7番目(の)", lesson: 2 },
  { english: "eighth", japanese: "8番目(の)", lesson: 2 },
  { english: "ninth", japanese: "9番目(の)", lesson: 2 },
  { english: "tenth", japanese: "10番目(の)", lesson: 2 },
  { english: "treasure", japanese: "財宝; 貴重品、宝物", lesson: 3 },
  { english: "camera", japanese: "カメラ", lesson: 3 },
  { english: "zucchini", japanese: "ズッキーニ", lesson: 3 },
  { english: "shop", japanese: "小売店、店", lesson: 3 },
  { english: "Japanese-style", japanese: "日本式の", lesson: 3 },
  { english: "open", japanese: "あいている、営業中で", lesson: 3 },
  { english: "from", japanese: "･･･から(の)", lesson: 3 },
  { english: "o'clock", japanese: "…時", lesson: 3 },
  { english: "this", japanese: "これ[が]、この人[が]", lesson: 3 },
  { english: "that", japanese: "それは[が]、あれは[が]", lesson: 3 },
  { english: "that's", japanese: "that isの短縮形", lesson: 3 },
  { english: "isn't", japanese: "is notの短縮形", lesson: 3 },
  { english: "we", japanese: "私たちは、私たちが", lesson: 3 },
  { english: "we're", japanese: "we areの短縮形", lesson: 3 },
  { english: "gate", japanese: "門", lesson: 3 },
  { english: "look", japanese: "ごらん、ほら、ちょっといいですか", lesson: 3 },
  { english: "that", japanese: "その、あの", lesson: 3 },
  { english: "scary", japanese: "恐ろしい、怖い", lesson: 3 },
  { english: "white", japanese: "白色の", lesson: 3 },
  { english: "statue", japanese: "像、彫像", lesson: 3 },
  { english: "chai", japanese: "チャイ", lesson: 3 },
  { english: "dictionary", japanese: "辞書、辞典", lesson: 3 },
  { english: "Ganesha", japanese: "ガネーシャ", lesson: 3 },
  { english: "is", japanese: "(･･･に)いる、(･･･に)ある", lesson: 3 },
  { english: "blackboard", japanese: "黒板", lesson: 3 },
  { english: "you're", japanese: "you areの短縮形", lesson: 3 },
  { english: "right", japanese: "正しい、まちがっていない", lesson: 3 },
  { english: "You're right.", japanese: "そのとおり。", lesson: 3 },
  { english: "correct", japanese: "正しい、正確な", lesson: 3 },
  { english: "almost", japanese: "ほとんど、おおかた", lesson: 3 },
  { english: "wrong", japanese: "まちがった", lesson: 3 },
  { english: "Indian", japanese: "インドの; インド人の", lesson: 3 },
  { english: "what", japanese: "何、どんなもの[こと]", lesson: 3 },
  { english: "what's", japanese: "what isの短縮形", lesson: 3 },
  { english: "a", japanese: "･･･というもの", lesson: 3 },
  { english: "sitar", japanese: "シタール", lesson: 3 },
  { english: "traditional", japanese: "伝統的な", lesson: 3 },
  { english: "musical", japanese: "音楽の", lesson: 3 },
  { english: "instrument", japanese: "楽器", lesson: 3 },
  { english: "little", japanese: "少し(は･･･する)", lesson: 3 },
  { english: "a little", japanese: "少し", lesson: 3 },
  { english: "online", japanese: "オンラインの", lesson: 3 },
  { english: "gift", japanese: "贈り物", lesson: 3 },
  { english: "from", japanese: "･･･から(の)", lesson: 3 },
  { english: "aunt", japanese: "おば", lesson: 3 },
  { english: "Harry", japanese: "ハリー", lesson: 3 },
  { english: "Snufkin", japanese: "スナフキン", lesson: 3 },
  { english: "who", japanese: "だれ、だれが", lesson: 3 },
  { english: "character", japanese: "人物; 登場人物", lesson: 3 },
  { english: "him", japanese: "彼を、彼に", lesson: 3 },
  { english: "much", japanese: "たいへん、大いに、とても", lesson: 3 },
  { english: "very much", japanese: "とても", lesson: 3 },
  { english: "who's", japanese: "who isの短縮形", lesson: 3 },
  { english: "know", japanese: "知り合いである、見知っている", lesson: 3 },
  { english: "nickname", japanese: "あだな", lesson: 3 },
  { english: "her", japanese: "彼女を、彼女に", lesson: 3 },
  { english: "with", japanese: "･･･を使って、･･･で", lesson: 3 },
  { english: "idea", japanese: "(ふとした)思いつき、考え、アイデア; 意見", lesson: 3 },
  { english: "room", japanese: "部屋、室", lesson: 3 },
  { english: "maybe", japanese: "たぶん、･･･かもしれない", lesson: 3 },
  { english: "man", japanese: "(おとなの) 男性", lesson: 3 },
  { english: "men", japanese: "man(男性)の複数形", lesson: 3 },
  { english: "excuse", japanese: "許す", lesson: 3 },
  { english: "Excuse me.", japanese: "すみません。", lesson: 3 },
  { english: "how", japanese: "どうやって、どんな方法で", lesson: 3 },
  { english: "get", japanese: "[･･･に]着く、達する", lesson: 3 },
  { english: "get to…", japanese: "･･･に着く", lesson: 3 },
  { english: "um", japanese: "うーん", lesson: 3 },
  { english: "straight", japanese: "まっすぐに", lesson: 3 },
  { english: "street", japanese: "通り、街路", lesson: 3 },
  { english: "carry", japanese: "運ぶ; 持っている", lesson: 3 },
  { english: "then", japanese: "それから次に、そのあと(で)", lesson: 3 },
  { english: "turn", japanese: "向きを変える; 曲がる", lesson: 3 },
  { english: "left", japanese: "左へ、左の方に", lesson: 3 },
  { english: "corner", japanese: "かど; 曲がりかど", lesson: 3 },
  { english: "on", japanese: "･･･に(接して[面して])", lesson: 3 },
  { english: "right", japanese: "右、右側", lesson: 3 },
  { english: "thank", japanese: "感謝する、ありがたいと思う", lesson: 3 },
  { english: "Thank you.", japanese: "ありがとう。", lesson: 3 },
  { english: "where", japanese: "どこに、どこで、どこへ", lesson: 3 },
  { english: "where's", japanese: "where isの短縮形", lesson: 3 },
  { english: "right", japanese: "右へ、右の方に[を]", lesson: 3 },
  { english: "left", japanese: "左、左側", lesson: 3 },
  { english: "plan", japanese: "計画、案、考え、予定", lesson: 4 },
  { english: "festival", japanese: "お祭り、祭典", lesson: 4 },
  { english: "firework", japanese: "花火;花火大会", lesson: 4 },
  { english: "with", japanese: "…と(いっしょに)、…とともに", lesson: 4 },
  { english: "family", japanese: "家族;一家", lesson: 4 },
  { english: "by", japanese: "…によって、…による", lesson: 4 },
  { english: "myself", japanese: "(私)自身で; 自分で", lesson: 4 },
  { english: "by oneself", japanese: "独力で", lesson: 4 },
  { english: "last", japanese: "(時間的に)この前の", lesson: 4 },
  { english: "year", japanese: "年、1年(間)", lesson: 4 },
  { english: "went", japanese: "go(行く)の過去形", lesson: 4 },
  { english: "hike", japanese: "ハイキングをする", lesson: 4 },
  { english: "Mt.", japanese: "山", lesson: 4 },
  { english: "saw", japanese: "see(見る)の過去形", lesson: 4 },
  { english: "view", japanese: "景色、ながめ", lesson: 4 },
  { english: "top", japanese: "いちばん上の部分、頂上;上部", lesson: 4 },
  { english: "was", japanese: "(…で)あった、…でした、…だった", lesson: 4 },
  { english: "ate", japanese: "eat(食べる)の過去形", lesson: 4 },
  { english: "thick", japanese: "分厚い", lesson: 4 },
  { english: "so", japanese: "非常に、とても、ずいぶん", lesson: 4 },
  { english: "good", japanese: "おいしい、(味の)いい", lesson: 4 },
  { english: "also", japanese: "…もまた; さらに、そのうえ", lesson: 4 },
  { english: "cheesecake", japanese: "チーズケーキ", lesson: 4 },
  { english: "for", japanese: "…として、…を意味する", lesson: 4 },
  { english: "kabuki", japanese: "歌舞伎", lesson: 4 },
  { english: "Mr.", japanese: "…氏、…さん、様、…先生", lesson: 4 },
  { english: "Korean", japanese: "韓国の; 韓国人[語]の", lesson: 4 },
  { english: "want", japanese: "(want to…の形で) …することを望む、…したい", lesson: 4 },
  { english: "to", japanese: "…すること", lesson: 4 },
  { english: "Seattle", japanese: "シアトル", lesson: 4 },
  { english: "hometown", japanese: "ふるさと、故郷", lesson: 4 },
  { english: "see", japanese: "会う; たずねて行く", lesson: 4 },
  { english: "baby", japanese: "赤ちゃん、〔形容詞的に〕赤ちゃんの", lesson: 4 },
  { english: "cousin", japanese: "いとこ", lesson: 4 },
  { english: "Seattle Dog", japanese: "シアトルドッグ", lesson: 4 },
  { english: "with", japanese: "…を持っている、…の付いている", lesson: 4 },
  { english: "cream cheese", japanese: "クリームチーズ", lesson: 4 },
  { english: "different", japanese: "いろいろな、さまざまな; 別々の", lesson: 4 },
  { english: "of", japanese: "…の", lesson: 4 },
  { english: "topping", japanese: "トッピング", lesson: 4 },
  { english: "boiled", japanese: "ゆでた、煮た", lesson: 4 },
  { english: "boiled egg", japanese: "ゆで卵", lesson: 4 },
  { english: "garlic", japanese: "ニンニク", lesson: 4 },
  { english: "fried garlic", japanese: "フライドガーリック、揚げたニンニク", lesson: 4 },
  { english: "dollar", japanese: "ドル", lesson: 4 },
  { english: "for", japanese: "…(の金額)で", lesson: 4 },
  { english: "free", japanese: "無料の", lesson: 4 },
  { english: "shrimp", japanese: "小エビ", lesson: 4 },
  { english: "mixed", japanese: "混合の、混ざった", lesson: 4 },
  { english: "clerk", japanese: "店員;従業員", lesson: 4 },
  { english: "would", japanese: "(…する)だろう、…でしょう; (…する)つもりだ、…しよう", lesson: 4 },
  { english: "What would you like?", japanese: "何になさいますか", lesson: 4 },
  { english: "I'd", japanese: "I wouldの短縮形", lesson: 4 },
  { english: "tuna", japanese: "マグロ", lesson: 4 },
  { english: "avocado", japanese: "アボカド", lesson: 4 },
  { english: "want", japanese: "(…が)ほしい、望む", lesson: 4 },
  { english: "anything", japanese: "(疑問文・条件文で)何か; (否定文で)何も(…ない)", lesson: 4 },
  { english: "orange", japanese: "オレンジの; オレンジ色の", lesson: 4 },
  { english: "much", japanese: "多量の、たくさんの、多くの", lesson: 4 },
  { english: "total", japanese: "合計", lesson: 4 },
  { english: "pick", japanese: "摘む", lesson: 4 },
  { english: "up", japanese: "上へ、上の方へ", lesson: 4 },
  { english: "pick up", japanese: "取りに行く、拾い上げる", lesson: 4 },
  { english: "order", japanese: "注文;注文の品", lesson: 4 },
  { english: "counter", japanese: "(銀行・商店などの)カウンター、勘定台", lesson: 4 },
  { english: "can", japanese: "(Can I…?の形で) …しましょうか", lesson: 4 },
  { english: "chair", japanese: "いす", lesson: 4 },
  { english: "desk", japanese: "机", lesson: 4 },
  { english: "shirt", japanese: "ワイシャツ、シャツ、ブラウス", lesson: 4 },
  { english: "train", japanese: "列車、電車", lesson: 4 },
  { english: "light", japanese: "軽い", lesson: 4 },
  { english: "heavy", japanese: "重い", lesson: 4 },
  { english: "thin", japanese: "薄い", lesson: 4 },
  { english: "protect", japanese: "保護する、守る", lesson: 4 },
  { english: "foot", japanese: "足", lesson: 4 },
  { english: "feet", japanese: "foot(足)の複数形", lesson: 4 },
  { english: "tell", japanese: "言う、話す、知らせる、教える", lesson: 4 },
  { english: "cool", japanese: "冷やす", lesson: 4 },
  { english: "useful", japanese: "役に立つ、便利な", lesson: 4 },
  { english: "in", japanese: "(時間を表して) …に; (時の経過を表して) …のうちに、…で", lesson: 4 },
  { english: "necessary", japanese: "必要な", lesson: 4 },
  { english: "for", japanese: "…のために[の]; …用に[の]", lesson: 4 },
  { english: "mother", japanese: "母、母親", lesson: 5 },
  { english: "live", japanese: "住む、住んでいる", lesson: 5 },
  { english: "London", japanese: "ロンドン", lesson: 5 },
  { english: "Betty", japanese: "ベティー", lesson: 5 },
  { english: "Sally", japanese: "サリー", lesson: 5 },
  { english: "at", japanese: "(時間の流れの一点、または短い期間を指して) …に", lesson: 5 },
  { english: "father", japanese: "父", lesson: 5 },
  { english: "taxi", japanese: "タクシー", lesson: 5 },
  { english: "driver", japanese: "(車の)運転手", lesson: 5 },
  { english: "know", japanese: "知っている; 知る; 気づいて[自覚して]いる", lesson: 5 },
  { english: "every", japanese: "すべての、あらゆる", lesson: 5 },
  { english: "tourist", japanese: "観光客、旅行者", lesson: 5 },
  { english: "place", japanese: "場所、所;地域", lesson: 5 },
  { english: "like", japanese: "…のように、…のような", lesson: 5 },
  { english: "Big Ben", japanese: "ビッグベン", lesson: 5 },
  { english: "big", japanese: "重要な;重大な、大変な", lesson: 5 },
  { english: "a big fan of …", japanese: "…の大ファン", lesson: 5 },
  { english: "football", japanese: "フットボール(用のボール)", lesson: 5 },
  { english: "they", japanese: "彼(女)らは[が]、それらは[が]; (ばく然と)人々(は)", lesson: 5 },
  { english: "wear", japanese: "身につけている; 着ている", lesson: 5 },
  { english: "their", japanese: "彼(女)らの; それらの", lesson: 5 },
  { english: "team", japanese: "チーム; (いっしょに活動する)団、組", lesson: 5 },
  { english: "uniform", japanese: "ユニフォーム", lesson: 5 },
  { english: "player", japanese: "(運動)選手、競技者", lesson: 5 },
  { english: "video", japanese: "テレビ(用)の; ビデオの; 動画の", lesson: 5 },
  { english: "game", japanese: "(一定のルールを持った)ゲーム、遊び", lesson: 5 },
  { english: "does", japanese: "doの3人称単数現在形", lesson: 5 },
  { english: "Ann", japanese: "アン", lesson: 5 },
  { english: "Maggie", japanese: "マギー", lesson: 5 },
  { english: "Sue", japanese: "スー", lesson: 5 },
  { english: "page", japanese: "ページ", lesson: 5 },
  { english: "doesn't", japanese: "does not の短縮形", lesson: 5 },
  { english: "brother", japanese: "兄、弟、(男の)兄弟", lesson: 5 },
  { english: "Peter", japanese: "ピーター", lesson: 5 },
  { english: "university", japanese: "大学", lesson: 5 },
  { english: "guitarist", japanese: "ギター奏者、ギタリスト", lesson: 5 },
  { english: "bagpipes", japanese: "バグパイプ", lesson: 5 },
  { english: "Scotland", japanese: "スコットランド", lesson: 5 },
  { english: "them", japanese: "彼(女)らを[に]、それらを[に]", lesson: 5 },
  { english: "concert", japanese: "演奏会、音楽会", lesson: 5 },
  { english: "performance", japanese: "上演、演奏、演技", lesson: 5 },
  { english: "internet", japanese: "(the internetで)インターネット", lesson: 5 },
  { english: "bye", japanese: "さよなら、じゃあね", lesson: 5 },
  { english: "See you.", japanese: "じゃあまた。", lesson: 5 },
  { english: "tomorrow", japanese: "あした(は)、あすは", lesson: 5 },
  { english: "wait", japanese: "待つ", lesson: 5 },
  { english: "whose", japanese: "だれの", lesson: 5 },
  { english: "towel", japanese: "タオル", lesson: 5 },
  { english: "yours", japanese: "あなたのもの; あなたたちのもの", lesson: 5 },
  { english: "mine", japanese: "私のもの", lesson: 5 },
  { english: "hers", japanese: "彼女のもの", lesson: 5 },
  { english: "bottle", japanese: "びん、ボトル", lesson: 5 },
  { english: "water bottle", japanese: "水筒", lesson: 5 },
  { english: "key", japanese: "鍵", lesson: 5 },
  { english: "cheerful", japanese: "元気のよい", lesson: 5 },
  { english: "clever", japanese: "利口な、頭のよい", lesson: 5 },
  { english: "easygoing", japanese: "あくせくしない", lesson: 5 },
  { english: "gentle", japanese: "(人・態度について)おだやかな、優しい;品のよい", lesson: 5 },
  { english: "honest", japanese: "正直な; 誠実な", lesson: 5 },
  { english: "world-famous", japanese: "世界的に有名な", lesson: 5 },
  { english: "Mario", japanese: "マリオ", lesson: 5 },
  { english: "why", japanese: "なぜ、どのようなわけで", lesson: 5 },
  { english: "Sherlock Holmes", japanese: "シャーロック・ホームズ", lesson: 5 },
  { english: "series", japanese: "(出版物・番組などの)シリーズ(物)", lesson: 5 },
  { english: "detective", japanese: "刑事;探偵", lesson: 5 },
  { english: "thing", japanese: "物;事", lesson: 5 },
  { english: "carefully", japanese: "注意深く、慎重に、念入りに", lesson: 5 },
  { english: "strange", japanese: "奇妙な、不思議な", lesson: 5 },
  { english: "fact", japanese: "事実", lesson: 5 },
  { english: "solve", japanese: "(問題などを)解決する、解く", lesson: 5 },
  { english: "difficult", japanese: "難しい、困難な;苦しい、厳しい", lesson: 5 },
  { english: "problem", japanese: "問題; やっかいなこと", lesson: 5 },
  { english: "well-known", japanese: "(一般的に)よく知られている; 有名な", lesson: 5 },
  { english: "tough", japanese: "ねばり強い、たくましい", lesson: 5 },
  { english: "confident", japanese: "確信した; 自信のある", lesson: 5 },
  { english: "mysterious", japanese: "神秘的な、なぞめいた", lesson: 5 },
  { english: "our", japanese: "私たちの、われわれの", lesson: 5 },
  { english: "us", japanese: "私たちを、私たちに", lesson: 5 },
  { english: "ours", japanese: "私たちのもの", lesson: 5 },
  { english: "his", japanese: "彼のもの", lesson: 5 },
  { english: "its", japanese: "その、それの", lesson: 5 },
  { english: "theirs", japanese: "彼(女)らのもの; それらのもの", lesson: 5 },
  { english: "here", japanese: "さあ、そら", lesson: 5 },
  { english: "Here is", japanese: "ここに…があります。", lesson: 5 },
  { english: "some", japanese: "いくつかの、いくらかの", lesson: 5 },
  { english: "reminder", japanese: "思い出させるもの", lesson: 5 },
  { english: "during", japanese: "…じゅうずっと…の間じゅう", lesson: 5 },
  { english: "each", japanese: "それぞれの、各…", lesson: 5 },
  { english: "throw", japanese: "投げること、投球", lesson: 5 },
  { english: "disturb", japanese: "じゃまをする、妨げる", lesson: 5 },
  { english: "clap", japanese: "(手を)たたく、拍手する", lesson: 5 },
  { english: "any", japanese: "(肯定文で)どんな…も、どの…も", lesson: 5 },
  { english: "personal", japanese: "個人的な、私的な", lesson: 5 },
  { english: "use", japanese: "使用;使用法、用途", lesson: 5 },
  { english: "under", japanese: "…の下に、…の下を[の、で]", lesson: 5 },
  { english: "belongings", japanese: "所有物、持ち物", lesson: 5 },
  { english: "seat", japanese: "座席; すわる物[所]", lesson: 5 },
  { english: "life", japanese: "生活、暮らし", lesson: 6 },
  { english: "Kevin", japanese: "ケビン (男性の名前)", lesson: 6 },
  { english: "is", japanese: "･･･している; (近い未来)･･･しようとしている", lesson: 6 },
  { english: "throw", japanese: "投げる", lesson: 6 },
  { english: "now", japanese: "今、今は、現在は", lesson: 6 },
  { english: "John", japanese: "ジョン (男性の名前)", lesson: 6 },
  { english: "Emily", japanese: "エミリー (女性の名前)", lesson: 6 },
  { english: "Brian", japanese: "ブライアン (男性の名前)", lesson: 6 },
  { english: "student", japanese: "学生、生徒", lesson: 6 },
  { english: "point", japanese: "さし示す、指さす", lesson: 6 },
  { english: "poster", japanese: "ポスター", lesson: 6 },
  { english: "choose", japanese: "選ぶ、選択する", lesson: 6 },
  { english: "own", japanese: "自分(自身)の、独特の", lesson: 6 },
  { english: "class", japanese: "授業", lesson: 6 },
  { english: "everyone", japanese: "だれでも、みんな", lesson: 6 },
  { english: "have", japanese: "(仕事などが)ある", lesson: 6 },
  { english: "has", japanese: "(仕事などが)ある", lesson: 6 },
  { english: "different", japanese: "違った、別の", lesson: 6 },
  { english: "schedule", japanese: "スケジュール、時間割", lesson: 6 },
  { english: "short", japanese: "(時間が)短い", lesson: 6 },
  { english: "break", japanese: "休憩", lesson: 6 },
  { english: "between", japanese: "(2つのもの・2人・2つの時刻)の間に", lesson: 6 },
  { english: "these", japanese: "これらの; この", lesson: 6 },
  { english: "are", japanese: "･･･している、(近い未来)･･･しようとしている", lesson: 6 },
  { english: "walk", japanese: "歩く、歩いて行く; 散歩をする", lesson: 6 },
  { english: "next", japanese: "(時間的に)次の、今度の", lesson: 6 },
  { english: "boy", japanese: "男の子、少年", lesson: 6 },
  { english: "hold", japanese: "(手などでしっかり)持っている、にぎる、抱く", lesson: 6 },
  { english: "flute", japanese: "フルート", lesson: 6 },
  { english: "girl", japanese: "女の子、少女", lesson: 6 },
  { english: "they're", japanese: "they are の短縮形", lesson: 6 },
  { english: "aren't", japanese: "are not の短縮形", lesson: 6 },
  { english: "some", japanese: "いくつかの、なかには…な人も[物]もある", lesson: 6 },
  { english: "some …, other(s)", japanese: "…もいれば[あれば]、〜もいる[ある]", lesson: 6 },
  { english: "buy", japanese: "買う", lesson: 6 },
  { english: "cafeteria", japanese: "セルフサービスの食堂", lesson: 6 },
  { english: "other", japanese: "ほかのもの[人]、別の物[人]", lesson: 6 },
  { english: "bring", japanese: "(物を)持ってくる; (人を)連れてくる", lesson: 6 },
  { english: "kind", japanese: "種類、種", lesson: 6 },
  { english: "of", japanese: "…の(入った)、…の量の; …の(種類の)", lesson: 6 },
  { english: "kind(s) of ~", japanese: "…種類の〜", lesson: 6 },
  { english: "well", japanese: "さあ、えーと; さて、ところで; まあ、そう(です)ね", lesson: 6 },
  { english: "common", japanese: "ふつうの、よくある; ありふれた", lesson: 6 },
  { english: "taco", japanese: "タコス", lesson: 6 },
  { english: "popular", japanese: "大衆的な; 一般的な", lesson: 6 },
  { english: "Mexican", japanese: "メキシコ(人)の", lesson: 6 },
  { english: "our", japanese: "私たちの、われわれの", lesson: 6 },
  { english: "at", japanese: "(ある場所にいて) …していて、…に従事して、…中で", lesson: 6 },
  { english: "I know", japanese: "そうですよね", lesson: 6 },
  { english: "excited", japanese: "興奮した、わくわくした", lesson: 6 },
  { english: "which", japanese: "どちらを、どれを", lesson: 6 },
  { english: "or", japanese: "または、あるいは; それとも", lesson: 6 },
  { english: "pasta", japanese: "パスタ", lesson: 6 },
  { english: "activity", japanese: "活動", lesson: 6 },
  { english: "field", japanese: "現場、現地、実地", lesson: 6 },
  { english: "trip", japanese: "旅行", lesson: 6 },
  { english: "field trip", japanese: "校外見学、野外研究、校外学習", lesson: 6 },
  { english: "contest", japanese: "コンテスト、コンクール", lesson: 6 },
  { english: "marathon", japanese: "マラソン競走", lesson: 6 },
  { english: "lunchtime", japanese: "昼食時間、昼休み", lesson: 6 },
  { english: "the", japanese: "(特定のものを指す定冠詞)", lesson: 6 },
  { english: "best", japanese: "最もよい、最高の", lesson: 6 },
  { english: "agree", japanese: "賛成する、同意する", lesson: 6 },
  { english: "dish", japanese: "料理", lesson: 6 },
  { english: "menu", japanese: "献立表、メニュー", lesson: 6 },
  { english: "dear", japanese: "親愛なる…", lesson: 6 },
  { english: "Spanish", japanese: "スペイン語", lesson: 6 },
  { english: "story", japanese: "物語、話", lesson: 6 },
  { english: "all", japanese: "すべての、全部の", lesson: 6 },
  { english: "foreign", japanese: "外国の", lesson: 6 },
  { english: "French", japanese: "フランス語", lesson: 6 },
  { english: "German", japanese: "ドイツ語", lesson: 6 },
  { english: "yours", japanese: "(いつまでも)あなたのもの", lesson: 6 },
  { english: "event", japanese: "(重要な)出来事、行事、イベント", lesson: 6 },
  { english: "vacation", japanese: "休暇、休み", lesson: 6 },
  { english: "entrance", japanese: "入ること、入場; 入学", lesson: 6 },
  { english: "ceremony", japanese: "式、式典", lesson: 6 },
  { english: "entrance ceremony", japanese: "入学式", lesson: 6 },
  { english: "by", japanese: "…によって、…で、…を使って", lesson: 6 },
  { english: "graduation", japanese: "卒業", lesson: 6 },
  { english: "graduation ceremony", japanese: "卒業式", lesson: 6 },
  { english: "serve", japanese: "(食べ物を食卓に)出す; (食事を人に)ふるまう", lesson: 6 },
  { english: "local", japanese: "地域の、その地方(特有)の、地元の", lesson: 6 },
  { english: "farmer", japanese: "農場主、農場経営者", lesson: 6 },
  { english: "stand", japanese: "売店、屋台", lesson: 6 },
  { english: "specialize", japanese: "(…を)専門に扱う", lesson: 6 },
  { english: "in", japanese: "…の点で、…に関して(は)、…に関する", lesson: 6 },
  { english: "specialize in …", japanese: "(…を)専門に扱う", lesson: 6 },
  { english: "handmade", japanese: "手作りの、手製の", lesson: 6 },
  { english: "candle", japanese: "ろうそく", lesson: 6 },
  { english: "organic", japanese: "有機栽培の", lesson: 6 },
  { english: "soap", japanese: "せっけん", lesson: 6 },
  { english: "support", japanese: "支持する、支援する", lesson: 6 },
  { english: "it", japanese: "(天候・気温・時間・距離などを表す)", lesson: 6 },
  { english: "noon", japanese: "正午、真昼、昼の12時", lesson: 6 },
  { english: "let's", japanese: "…しましょう", lesson: 6 },
  { english: "feel", japanese: "(体や心に)感じる", lesson: 6 },
  { english: "well", japanese: "健康で[な]、元気で[に]", lesson: 6 },
  { english: "what", japanese: "何が", lesson: 6 },
  { english: "wrong", japanese: "調子[具合]が悪い、故障した", lesson: 6 },
  { english: "have", japanese: "(経験として)持つ、…する; (病気に)かかっている", lesson: 6 },
  { english: "headache", japanese: "頭痛", lesson: 6 },
  { english: "sick", japanese: "病気の; 気分が悪い", lesson: 6 },
  { english: "find", japanese: "見つける、見いだす", lesson: 6 },
  { english: "bench", japanese: "長いす、ベンチ", lesson: 6 },
  { english: "and", japanese: "そして(それから)", lesson: 6 },
  { english: "sit", japanese: "すわっている; すわる", lesson: 6 },
  { english: "down", japanese: "(上から下への動きを表して)下へ[に]、下の方へ[に]", lesson: 6 },
  { english: "thank", japanese: "感謝", lesson: 6 },
  { english: "matter", japanese: "問題; 困った事", lesson: 6 },
  { english: "OK", japanese: "よろしい、問題ない、オーケー", lesson: 6 },
  { english: "rest", japanese: "休息、休養; 休けい", lesson: 6 },
  { english: "stomachache", japanese: "腹痛、胃痛", lesson: 6 },
  { english: "dizzy", japanese: "めまいがする、くらくらする", lesson: 6 },
  { english: "fever", japanese: "熱", lesson: 6 },
  { english: "twisted", japanese: "(足首などが)ねんざした", lesson: 6 },
  { english: "ankle", japanese: "足首、くるぶし", lesson: 6 },
  { english: "athlete", japanese: "運動選手", lesson: 7 },
  { english: "spirit", japanese: "心、精神", lesson: 7 },
  { english: "Paralympics", japanese: "パラリンピック競技会", lesson: 7 },
  { english: "get", japanese: "手に入れる、得る、もらう", lesson: 7 },
  { english: "got", japanese: "get (手に入れる)の過去形・過去分詞", lesson: 7 },
  { english: "award", japanese: "賞、賞品", lesson: 7 },
  { english: "join", japanese: "参加する、加わる", lesson: 7 },
  { english: "program", japanese: "番組(表); プログラム", lesson: 7 },
  { english: "start", japanese: "始める; 始まる", lesson: 7 },
  { english: "age", japanese: "(人間・動物・物の) 年齢", lesson: 7 },
  { english: "have", japanese: "(思い・考えなどを) 心に持っている、いだく", lesson: 7 },
  { english: "had", japanese: "have (心に持っている)の過去形・過去分詞", lesson: 7 },
  { english: "goal", japanese: "目標、目的", lesson: 7 },
  { english: "be", japanese: "(･･･で) ある; (･･･に) なる", lesson: 7 },
  { english: "shooter", japanese: "(球技で) シュートする人", lesson: 7 },
  { english: "first", japanese: "第一に; 最初に、まず", lesson: 7 },
  { english: "set", japanese: "設定する; 用意する; (時計などを) 合わせる", lesson: 7 },
  { english: "shoot", japanese: "シュートする", lesson: 7 },
  { english: "hand", japanese: "手", lesson: 7 },
  { english: "quickly", japanese: "すばやく、速く", lesson: 7 },
  { english: "reach", japanese: "･･･に着く、到達する、(･･･まで) 達する", lesson: 7 },
  { english: "by", japanese: "･･･ごとに", lesson: 7 },
  { english: "one by one", japanese: "1つ [1人]ずつ", lesson: 7 },
  { english: "finally", japanese: "ついに、最後に", lesson: 7 },
  { english: "become", japanese: "･･･になる", lesson: 7 },
  { english: "became", japanese: "become (･･･になる)の過去形", lesson: 7 },
  { english: "advice", japanese: "忠告、助言、アドバイス", lesson: 7 },
  { english: "small", japanese: "ささいな", lesson: 7 },
  { english: "score", japanese: "得点する", lesson: 7 },
  { english: "point", japanese: "(競技・成績の) 点数、得点", lesson: 7 },
  { english: "did", japanese: "doの過去形", lesson: 7 },
  { english: "magazine", japanese: "雑誌、定期刊行物", lesson: 7 },
  { english: "yesterday", japanese: "きのう(は)", lesson: 7 },
  { english: "didn't", japanese: "did notの短縮形", lesson: 7 },
  { english: "successful", japanese: "成功した、うまくいった", lesson: 7 },
  { english: "on", japanese: "･･･について(の)、･･･に関する; 〔所属を表して〕", lesson: 7 },
  { english: "at first", japanese: "最初は", lesson: 7 },
  { english: "copy", japanese: "まねる", lesson: 7 },
  { english: "top", japanese: "いちばん上の; 最高(位)の; 上位", lesson: 7 },
  { english: "style", japanese: "様式、流儀、やり方", lesson: 7 },
  { english: "hard", japanese: "一生懸命に、熱心に", lesson: 7 },
  { english: "but", japanese: "しかし、(だ)が、けれども", lesson: 7 },
  { english: "could", japanese: "･･･することができた", lesson: 7 },
  { english: "couldn't", japanese: "could notの短縮形", lesson: 7 },
  { english: "change", japanese: "変える; 変わる、変化する", lesson: 7 },
  { english: "mind", japanese: "心、精神; 考え", lesson: 7 },
  { english: "focus", japanese: "(注意などを) 集中する", lesson: 7 },
  { english: "on", japanese: "･･･に対して", lesson: 7 },
  { english: "focus on", japanese: "･･･に焦点を合わせる", lesson: 7 },
  { english: "anymore", japanese: "もはや; これ以上", lesson: 7 },
  { english: "way", japanese: "方法、やり方、しかた", lesson: 7 },
  { english: "in one's own way", japanese: "自分のやり方で", lesson: 7 },
  { english: "all-around", japanese: "万能の、多才な", lesson: 7 },
  { english: "people", japanese: "人々; 世間(の人々)", lesson: 7 },
  { english: "Olympic", japanese: "オリンピックの", lesson: 7 },
  { english: "its", japanese: "その、それの", lesson: 7 },
  { english: "energy", japanese: "元気、(心身の) 力", lesson: 7 },
  { english: "skateboarder", japanese: "スケートボーダー", lesson: 7 },
  { english: "amazing", japanese: "驚くべき、驚くほどの、みごとな", lesson: 7 },
  { english: "trick", japanese: "芸当、技", lesson: 7 },
  { english: "hug", japanese: "抱きしめる", lesson: 7 },
  { english: "rival", japanese: "競争相手、ライバル", lesson: 7 },
  { english: "even", japanese: "･･･でさえ、･･･でも", lesson: 7 },
  { english: "practice", japanese: "練習", lesson: 7 },
  { english: "cheer", japanese: "声援する、元気づける", lesson: 7 },
  { english: "each", japanese: "それぞれ", lesson: 7 },
  { english: "other", japanese: "(2つの中で) もう一方(のもの); (3つ以上の中で) 残りのもの", lesson: 7 },
  { english: "each other", japanese: "おたがい(を[に])", lesson: 7 },
  { english: "on", japanese: "(どんどん) 続けて、先へ", lesson: 7 },
  { english: "try", japanese: "努力する、努める", lesson: 7 },
  { english: "again", japanese: "もう一度、また、再び", lesson: 7 },
  { english: "and", japanese: "･･･も･･･も", lesson: 7 },
  { english: "again and again", japanese: "何度も何度も", lesson: 7 },
  { english: "not always", japanese: "いつも･･･とは限らない", lesson: 7 },
  { english: "succeed", japanese: "成功する", lesson: 7 },
  { english: "themselves", japanese: "彼(女)ら自身(を[に]); それら自体(を[に])", lesson: 7 },
  { english: "not", japanese: "･･･でない", lesson: 7 },
  { english: "only", japanese: "ただ･･･だけ", lesson: 7 },
  { english: "victory", japanese: "勝利", lesson: 7 },
  { english: "learn", japanese: "動学ぶ、習う;覚える", lesson: 7 },
  { english: "this", japanese: "④ 今述べたこと;次に述べること", lesson: 7 },
  { english: "Olympics", japanese: "国際オリンピック競技会", lesson: 7 },
  { english: "national", japanese: "国の、国立の、国家の", lesson: 7 },
  { english: "curling", japanese: "カーリング", lesson: 7 },
  { english: "during", japanese: "･･･の間(のいつか)に、･･･の期間中に連続的に【何度も]", lesson: 7 },
  { english: "make", japanese: "作る、･･･する", lesson: 7 },
  { english: "made", japanese: "make (作る、･･･する)の過去形・過去分詞", lesson: 7 },
  { english: "shot", japanese: "⑧ ショット、一打", lesson: 7 },
  { english: "teammate", japanese: "名 チームメイト", lesson: 7 },
  { english: "for", japanese: "関連を表して〕･･･について(は);", lesson: 7 },
  { english: "help", japanese: "名 手伝い、助け", lesson: 7 },
  { english: "bad", japanese: "悪い; よくない", lesson: 7 },
  { english: "give", japanese: "動(ある動作を)する", lesson: 7 },
  { english: "gave", japanese: "give ((ある動作を)する)の過去形", lesson: 7 },
  { english: "high five", japanese: "ハイタッチ", lesson: 7 },
  { english: "show", japanese: "動見せる、示す", lesson: 7 },
  { english: "support", japanese: "支持、支援", lesson: 7 },
  { english: "positive", japanese: "前向きな、積極的な", lesson: 7 },
  { english: "communication", japanese: "意思の疎通、コミュニケーション", lesson: 7 },
  { english: "topic", japanese: "⑧話題;(講演・エッセイなどの) テーマ", lesson: 7 },
  { english: "robot", japanese: "名 ロボット", lesson: 7 },
  { english: "apply", japanese: "■申し込む、応募する", lesson: 7 },
  { english: "describe", japanese: "■詳細に述べる、記述する", lesson: 7 },
  { english: "form", japanese: "(書き込み) 用紙;書式", lesson: 7 },
  { english: "include", japanese: "含む;含める", lesson: 7 },
  { english: "point", japanese: "要点;論点;(よい [悪い])点", lesson: 7 },
  { english: "key", japanese: "重要な、かぎとなる", lesson: 7 },
  { english: "creative", japanese: "創造力のある; 独創的な", lesson: 7 },
  { english: "size", japanese: "大きさ", lesson: 7 },
  { english: "meter", japanese: "名 メートル", lesson: 7 },
  { english: "tall", japanese: "背が高い、身長 [高さ]が･･･ある", lesson: 7 },
  { english: "automatically", japanese: "自動的に", lesson: 7 },
  { english: "heat", japanese: "熱する、暖める", lesson: 7 },
  { english: "use", japanese: "費やす、消費する", lesson: 7 },
  { english: "lot", japanese: "たくさん", lesson: 7 },
  { english: "a lot of…", japanese: "たくさんの･･･", lesson: 7 },
  { english: "electricity", japanese: "名電気", lesson: 7 },
  { english: "gram", japanese: "グラム", lesson: 7 },
  { english: "remove", japanese: "取りはずす、取り除く", lesson: 7 },
  { english: "dust", japanese: "⑧ちり、ごみ、ほこり", lesson: 7 },
  { english: "floor", japanese: "名床", lesson: 7 },
  { english: "window", japanese: "名窓", lesson: 7 },
  { english: "up", japanese: "･･･を上がって、･･･の上(の方)へ[に]", lesson: 7 },
  { english: "stair", japanese: "階段", lesson: 7 },
  { english: "trash", japanese: "名ごみ", lesson: 7 },
  { english: "climb", japanese: "動登る、(両手両足で)よじ登る", lesson: 7 },
  { english: "tree", japanese: "⑧木、樹木", lesson: 7 },
  { english: "fly", japanese: "動飛ぶ", lesson: 7 },
  { english: "high", japanese: "副高く", lesson: 7 },
  { english: "help", japanese: "動(人を)手伝う、助ける", lesson: 7 },
  { english: "teacher", japanese: "名先生、教師", lesson: 7 },
  { english: "care", japanese: "世話、保護", lesson: 7 },
  { english: "of", japanese: "前〔意味上の目的語を表して〕･･･の", lesson: 7 },
  { english: "take care of…", japanese: "･･･の世話をする", lesson: 7 },
  { english: "look", japanese: "動(外見が)･･･に見える", lesson: 7 },
  { english: "look like…", japanese: "･･･のように見える、･･･に似ている", lesson: 7 },
  { english: "Alice", japanese: "名 アリス (◎女性の名前)", lesson: 7 },
  { english: "Humpty Dumpty", japanese: "ハンプティ・ダンプティ", lesson: 7 },
  { english: "pocket", japanese: "ポケット", lesson: 7 },
  { english: "late", japanese: "(本来の時間・予定より)遅い、(時間に)遅れた", lesson: 7 },
  { english: "into", japanese: "前〔内部への動きを表して〕･･･の中へ[に]", lesson: 7 },
  { english: "hole", japanese: "名穴", lesson: 7 },
  { english: "follow", japanese: "動(･･･のあとに)ついて行く; 追う", lesson: 7 },
  { english: "fall", japanese: "落ちる", lesson: 7 },
  { english: "Wonderland", japanese: "名(童話の) 不思議の国", lesson: 7 },
  { english: "high", japanese: "高い", lesson: 7 },
  { english: "wall", japanese: "⑧へい;城壁", lesson: 7 },
  { english: "say", japanese: "言う、話す、述べる", lesson: 7 },
  { english: "said", japanese: "say (言う)の過去形・過去分詞)", lesson: 7 },
  { english: "name", japanese: "名前", lesson: 7 },
  { english: "little", japanese: "形小さい、年少の", lesson: 7 },
  { english: "mean", japanese: "意味する、･･･の意味である", lesson: 7 },
  { english: "something", japanese: "代何か、あるもの", lesson: 7 },
  { english: "ask", japanese: "(･･･について) たずねる、問う", lesson: 7 },
  { english: "course", japanese: "⑧[of courseで]もちろん、確かに", lesson: 7 },
  { english: "Of course.", japanese: "もちろん。", lesson: 7 },
  { english: "belt", japanese: "ベルト、帯", lesson: 7 },
  { english: "tie", japanese: "ネクタイ", lesson: 7 },
  { english: "around", japanese: "･･･のまわりを[に]、･･･の周囲を[に]、･･･をぐるりと", lesson: 7 },
  { english: "neck", japanese: "首", lesson: 7 },
  { english: "lovely", japanese: "愛らしい、かわいい", lesson: 7 },
  { english: "anyway", japanese: "副ところで", lesson: 7 },
  { english: "careful", japanese: "注意深い、慎重な", lesson: 7 },
  { english: "sat", japanese: "sit (すわっている)の過去形・過去分詞", lesson: 7 },
  { english: "have", japanese: "動(･･･を)する", lesson: 7 },
  { english: "great", japanese: "(びっくりするほど)(規模が)大きい;(程度が)非常な", lesson: 7 },
  { english: "fall", japanese: "⑧落ちること、落下", lesson: 7 },
  { english: "stop", japanese: "動やめる、やめさせる", lesson: 7 },
  { english: "do", japanese: "･･･するな", lesson: 7 },
  { english: "terrible", japanese: "形恐ろしい、ひどい", lesson: 7 },
  { english: "cry", japanese: "叫ぶ、大声で言う", lesson: 7 },
  { english: "not", japanese: "何も･･･ない、少しも･･･ない", lesson: 7 },
  { english: "all", japanese: "代すべての人、すべてのもの[こと]", lesson: 7 },
  { english: "not… at all", japanese: "少しも･･･ない", lesson: 7 },
  { english: "hate", japanese: "憎む、ひどく嫌う", lesson: 7 },
  { english: "discover", japanese: "発見する、見つける", lesson: 8 },
  { english: "sunny", japanese: "日の照っている、晴れた", lesson: 8 },
  { english: "leaf", japanese: "葉", lesson: 8 },
  { english: "were", japanese: "であった、でした、だった", lesson: 8 },
  { english: "garden", japanese: "庭、庭園、畑、菜園", lesson: 8 },
  { english: "city", japanese: "市の、都会の", lesson: 8 },
  { english: "light", japanese: "明かり、電灯", lesson: 8 },
  { english: "airport", japanese: "空港", lesson: 8 },
  { english: "boring", japanese: "退屈な、うんざりさせる", lesson: 8 },
  { english: "surprised", japanese: "驚いた", lesson: 8 },
  { english: "the", japanese: "(年)代、今、当", lesson: 8 },
  { english: "win", japanese: "勝つ", lesson: 8 },
  { english: "lose", japanese: "負ける", lesson: 8 },
  { english: "won", japanese: "win (勝つ)の過去形・過去分詞", lesson: 8 },
  { english: "travel", japanese: "旅行する、旅をする", lesson: 8 },
  { english: "rode", japanese: "ride (乗る)の過去形", lesson: 8 },
  { english: "along", japanese: "(道・川など)に沿って", lesson: 8 },
  { english: "colorful", japanese: "色彩に富んだ、色とりどりの、カラフルな", lesson: 8 },
  { english: "wore", japanese: "wear (身につけている)の過去形", lesson: 8 },
  { english: "kimono", japanese: "着物", lesson: 8 },
  { english: "across", japanese: "を横切って、を横断して、の向こう側へ", lesson: 8 },
  { english: "bridge", japanese: "橋", lesson: 8 },
  { english: "tea ceremony", japanese: "茶道", lesson: 8 },
  { english: "drank", japanese: "drink (飲む)の過去形", lesson: 8 },
  { english: "sweet", japanese: "甘い菓子", lesson: 8 },
  { english: "Japanese", japanese: "日本の、日本人の、日本語の", lesson: 8 },
  { english: "was", japanese: "していた", lesson: 8 },
  { english: "ski", japanese: "スキーですべる", lesson: 8 },
  { english: "then", japanese: "その時、当時", lesson: 8 },
  { english: "were", japanese: "していた", lesson: 8 },
  { english: "hmm", japanese: "ふうむ", lesson: 8 },
  { english: "at that time", japanese: "その時には", lesson: 8 },
  { english: "radio", japanese: "ラジオ(放送)", lesson: 8 },
  { english: "how", japanese: "どんなぐあいで、どんな状態で、いかがで", lesson: 8 },
  { english: "wonderful", japanese: "すばらしい、とてもすてきな", lesson: 8 },
  { english: "stay", japanese: "とどまる、いる、滞在する", lesson: 8 },
  { english: "hold", japanese: "(会などを)開く、催す、行う", lesson: 8 },
  { english: "held", japanese: "hold ((会などを)開く)の過去形・過去分詞", lesson: 8 },
  { english: "quite", japanese: "ほんとに、とても、かなり", lesson: 8 },
  { english: "lonely", japanese: "孤独な、さびしい", lesson: 8 },
  { english: "up", japanese: "起きて", lesson: 8 },
  { english: "What's up?", japanese: "どうしたのですか", lesson: 8 },
  { english: "yeah", japanese: "ああ、わかっているよ", lesson: 8 },
  { english: "give", japanese: "与える、あげる、渡す", lesson: 8 },
  { english: "souvenir", japanese: "みやげ物", lesson: 8 },
  { english: "luck", japanese: "運、幸運", lesson: 8 },
  { english: "charm", japanese: "お守り", lesson: 8 },
  { english: "blue", japanese: "青色の、青ざめた", lesson: 8 },
  { english: "rainy", japanese: "雨の、雨降りの", lesson: 8 },
  { english: "today", japanese: "きょう(は)", lesson: 8 },
  { english: "miss", japanese: "機会を逃す", lesson: 8 },
  { english: "spring", japanese: "泉", lesson: 8 },
  { english: "hot spring", japanese: "温泉", lesson: 8 },
  { english: "barbecue", japanese: "バーベキュー", lesson: 8 },
  { english: "play", japanese: "遊ぶ", lesson: 8 },
  { english: "snow", japanese: "雪", lesson: 8 },
  { english: "neighbor", japanese: "近所の人", lesson: 8 },
  { english: "bus", japanese: "バス", lesson: 8 },
  { english: "plane", japanese: "飛行機", lesson: 8 },
  { english: "airplane", japanese: "飛行機", lesson: 8 },
  { english: "visit", japanese: "(人を)訪問する、訪ねる", lesson: 8 },
  { english: "grandfather", japanese: "祖父、おじいさん", lesson: 8 },
  { english: "with", japanese: "とともに、と同時に", lesson: 8 },
  { english: "here", japanese: "ここにいる、この", lesson: 8 },
  { english: "die", japanese: "(人・動物などが) 死ぬ、(植物が)枯れる", lesson: 8 },
  { english: "remember", japanese: "覚えている、忘れていない、思い出す", lesson: 8 },
  { english: "war", japanese: "戦争", lesson: 8 },
  { english: "pray", japanese: "祈る、祈願する", lesson: 8 },
  { english: "for", japanese: "を求めて、のために", lesson: 8 },
  { english: "peace", japanese: "平和", lesson: 8 },
  { english: "silence", japanese: "静けさ、沈黙", lesson: 8 },
  { english: "this", japanese: "今の、今、この、きょうの、現在の", lesson: 8 },
  { english: "moment", japanese: "ちょっとの時間、瞬間", lesson: 8 },
  { english: "touch", japanese: "(胸) (心)を打つ、感動させる", lesson: 8 },
  { english: "heart", japanese: "心", lesson: 8 },
  { english: "touch one's heart", japanese: "感動させる", lesson: 8 },
  { english: "ran", japanese: "run (走る)の過去形", lesson: 8 },
  { english: "kilometer", japanese: "キロメートル", lesson: 8 },
  { english: "long", japanese: "の間中、ずっと", lesson: 8 },
  { english: "all day long", japanese: "一日中", lesson: 8 },
  { english: "spend", japanese: "(時間を)過ごす、費やす", lesson: 8 },
  { english: "spent", japanese: "spend ((時間を)過ごす)の過去形・過去分詞", lesson: 8 },
  { english: "time", japanese: "時、時間、必要な時間", lesson: 8 },
  { english: "grandmother", japanese: "祖母、おばあさん", lesson: 8 },
  { english: "took", japanese: "take (取る)の過去形", lesson: 8 },
  { english: "drop", japanese: "落とす、落ちる", lesson: 8 },
  { english: "purse", japanese: "さいふ", lesson: 8 },
  { english: "match", japanese: "試合、競技", lesson: 8 },
  { english: "cafe", japanese: "レストラン、カフェ", lesson: 8 },
  { english: "college", japanese: "大学", lesson: 8 },
  { english: "land", japanese: "土地", lesson: 8 },
  { english: "missing", japanese: "行方不明の", lesson: 8 },
  { english: "emergency", japanese: "非常時、緊急事態、緊急時の", lesson: 9 },
  { english: "will", japanese: "･･(する)でしょう、･･･(する)だろう", lesson: 9 },
  { english: "city", japanese: "市、都市、都会", lesson: 9 },
  { english: "near", japanese: "･･･の近くに、･･･の近くの", lesson: 9 },
  { english: "ocean", japanese: "大洋、大海、海", lesson: 9 },
  { english: "I'll", japanese: "I willの短縮形", lesson: 9 },
  { english: "it'll", japanese: "it willの短縮形", lesson: 9 },
  { english: "won't", japanese: "will notの短縮形", lesson: 9 },
  { english: "tasteless", japanese: "味のない、まずい", lesson: 9 },
  { english: "tasty", japanese: "風味のよい、おいしい", lesson: 9 },
  { english: "image", japanese: "印象、イメージ", lesson: 9 },
  { english: "prepare", japanese: "用意する、準備をする", lesson: 9 },
  { english: "time", japanese: "…度、…回、(ある長さの)時間、期間、…なひと時", lesson: 9 },
  { english: "for the first time", japanese: "初めて", lesson: 9 },
  { english: "warm", japanese: "暖かい、温かい", lesson: 9 },
  { english: "cool", japanese: "涼しい、冷えた", lesson: 9 },
  { english: "make", japanese: "(使えるような状態に)整える、用意する", lesson: 9 },
  { english: "easily", japanese: "楽々と、容易に", lesson: 9 },
  { english: "supermarket", japanese: "スーパーマーケット、スーパー", lesson: 9 },
  { english: "type", japanese: "型、タイプ、種類", lesson: 9 },
  { english: "you'll", japanese: "you willの短縮形", lesson: 9 },
  { english: "go", japanese: "…しようとしている、…するつもりである", lesson: 9 },
  { english: "How about you?", japanese: "あなたはどうですか。", lesson: 9 },
  { english: "recommend", japanese: "推薦する、推奨する", lesson: 9 },
  { english: "familiar", japanese: "よく知っている、なじみのある", lesson: 9 },
  { english: "mean", japanese: "(人が)･･･のことを言う", lesson: 9 },
  { english: "probably", japanese: "おそらく、たぶん", lesson: 9 },
  { english: "scared", japanese: "おびえた", lesson: 9 },
  { english: "disaster", japanese: "大災害、惨事", lesson: 9 },
  { english: "comfort", japanese: "元気づける", lesson: 9 },
  { english: "for", japanese: "･･･にとって", lesson: 9 },
  { english: "so", japanese: "そういうわけで、それで", lesson: 9 },
  { english: "keep", japanese: "持ち続ける、保存する、とっておく", lesson: 9 },
  { english: "instant", japanese: "即席の、インスタントの", lesson: 9 },
  { english: "look for …", japanese: "…をさがす", lesson: 9 },
  { english: "that", japanese: "それを[に]、あれを[に]", lesson: 9 },
  { english: "natural", japanese: "天然の、自然の", lesson: 9 },
  { english: "frequently", japanese: "しばしば、頻繁に", lesson: 9 },
  { english: "occur", japanese: "(事件などが)起こる", lesson: 9 },
  { english: "everybody", japanese: "だれでも、みんな", lesson: 9 },
  { english: "need", japanese: "…が必要である、…を必要とする", lesson: 9 },
  { english: "their", japanese: "(その)人の、自分の", lesson: 9 },
  { english: "go bag", japanese: "非常持ち出し袋", lesson: 9 },
  { english: "found", japanese: "find (見つける)の過去形・過去分詞", lesson: 9 },
  { english: "example", japanese: "例、実例", lesson: 9 },
  { english: "group", japanese: "(人・動物・植物・物などの)集団、グループ", lesson: 9 },
  { english: "invent", japanese: "発明する、考え出す", lesson: 9 },
  { english: "pack", japanese: "包み、パック", lesson: 9 },
  { english: "long-lasting", japanese: "長持ちする", lesson: 9 },
  { english: "addition", japanese: "付け加えること、付け加わったもの", lesson: 9 },
  { english: "in addition", japanese: "さらに", lesson: 9 },
  { english: "shelter", japanese: "(風雨・攻撃などから)守ってくれる物[場所]、避難所", lesson: 9 },
  { english: "chose", japanese: "choose(選ぶ)の過去形", lesson: 9 },
  { english: "company", japanese: "会社", lesson: 9 },
  { english: "region", japanese: "地域、地方", lesson: 9 },
  { english: "and", japanese: "それで、だから", lesson: 9 },
  { english: "work", japanese: "働く、仕事をする", lesson: 9 },
  { english: "bring", japanese: "(知らせ・ある状態・出来事などを)もたらす", lesson: 9 },
  { english: "tough", japanese: "つらい、苦しい、困難な", lesson: 9 },
  { english: "important", japanese: "重要な、重大な、大切な", lesson: 9 },
  { english: "part", japanese: "役割", lesson: 9 },
  { english: "bar", japanese: "棒、延べ棒、棒状の物", lesson: 9 },
  { english: "put", japanese: "(ある場所に)置く、付ける", lesson: 9 },
  { english: "holiday", japanese: "祝日、休日", lesson: 9 },
  { english: "cloudy", japanese: "くもりの、くもった", lesson: 9 },
  { english: "clear", japanese: "澄んだ、晴れた、快晴の", lesson: 9 },
  { english: "high", japanese: "最高水準", lesson: 9 },
  { english: "low", japanese: "低い水準[数値]", lesson: 9 },
  { english: "degree", japanese: "(温度・角度などの)度", lesson: 9 },
  { english: "am", japanese: "…している、(近い将来)…しようとしている", lesson: 9 },
  { english: "cut", japanese: "切る、刈る", lesson: 9 },
  { english: "sorry", japanese: "すまなく思って、後悔して", lesson: 9 },
  { english: "slimy", japanese: "ぬるぬるした", lesson: 9 },
  { english: "touch", japanese: "触れる、さわる", lesson: 9 },
  { english: "OK", japanese: "オーケー、よろしい", lesson: 9 },
  { english: "then", japanese: "それなら、それでは、そうすると", lesson: 9 },
  { english: "all", japanese: "まったく、すっかり", lesson: 9 },
  { english: "All right.", japanese: "よろしい。", lesson: 9 },
  { english: "news", japanese: "知らせ、ニュース、報道", lesson: 9 },
  { english: "rain", japanese: "雨が降る", lesson: 9 },
  { english: "no", japanese: "無の1つも…ない、何も…ない", lesson: 9 },
  { english: "No problem.", japanese: "いいですよ、問題ない。", lesson: 9 },
  { english: "I'm sorry.", japanese: "すみません", lesson: 9 },
  { english: "busy", japanese: "忙しい", lesson: 9 },
  { english: "fire", japanese: "火、炎", lesson: 9 },
  { english: "once", japanese: "かつて、昔", lesson: 9 },
  { english: "upon", japanese: "onとほぼ同じ", lesson: 9 },
  { english: "once upon a time", japanese: "昔々", lesson: 9 },
  { english: "child", japanese: "子ども", lesson: 9 },
  { english: "children", japanese: "child (子ども)の複数形", lesson: 9 },
  { english: "bully", japanese: "いじめる、おどす", lesson: 9 },
  { english: "turtle", japanese: "カメ", lesson: 9 },
  { english: "few", japanese: "少数の、少しの", lesson: 9 },
  { english: "a few", japanese: "少数の･･･", lesson: 9 },
  { english: "come", japanese: "来る、到着する", lesson: 9 },
  { english: "came", japanese: "come (来る)の過去形", lesson: 9 },
  { english: "there", japanese: "そこに、そこで、そこへ、あそこに[で、へ]", lesson: 9 },
  { english: "welcome", japanese: "歓迎する、迎える", lesson: 9 },
  { english: "have fun", japanese: "楽しむ", lesson: 9 },
  { english: "one", japanese: "ある…", lesson: 9 },
  { english: "one day", japanese: "ある日", lesson: 9 },
  { english: "village", japanese: "村、村落", lesson: 9 },
  { english: "everything", japanese: "すべてのこと[物]、何もかも", lesson: 9 },
  { english: "villager", japanese: "村人、村民", lesson: 9 },
  { english: "respond", japanese: "(…に)答える", lesson: 9 },
  { english: "disappear", japanese: "見えなくなる、姿を消す、消えうせる", lesson: 9 },
  { english: "ago", japanese: "(今から)…前に", lesson: 9 },
  { english: "open", japanese: "(ドア・窓などが)開く、あける", lesson: 9 },
  { english: "empty", japanese: "からの", lesson: 9 },
  { english: "smoke", japanese: "煙", lesson: 9 },
  { english: "come", japanese: "起こる、現れてくる", lesson: 9 },
  { english: "come out of …", japanese: "…から出てくる、(考えなどが)浮かぶ", lesson: 9 },
  { english: "turn", japanese: "変わる、…になる", lesson: 9 },
  { english: "into", japanese: "…(の状態)に(なって)、…(の状態)に(変わって)", lesson: 9 },
  { english: "turn into …", japanese: "…に変わる", lesson: 9 },
  { english: "old", japanese: "年とった、年老いた", lesson: 9 },
  { english: "long", japanese: "ずっと(前に、あとに)", lesson: 9 },
  { english: "woman", japanese: "(おとなの)女性", lesson: 9 },
  { english: "women", japanese: "woman(女性)の複数形", lesson: 9 },
  { english: "live", japanese: "暮らす、生活する", lesson: 9 },
  { english: "collect", japanese: "集める、収集する", lesson: 9 },
  { english: "wood", japanese: "木、まき、たきぎ", lesson: 9 },
  { english: "plant", japanese: "植物、草", lesson: 9 },
  { english: "forest", japanese: "森林", lesson: 9 },
  { english: "special", japanese: "特別な、大事な", lesson: 9 },
  { english: "bamboo", japanese: "竹", lesson: 9 },
  { english: "shine", japanese: "輝く、光る", lesson: 9 },
  { english: "off", japanese: "離れて、去って、(乗り物から)降りて、(物を)離して、取って", lesson: 9 },
  { english: "cut off", japanese: "切り離す", lesson: 9 },
  { english: "wife", japanese: "妻", lesson: 9 },
  { english: "together", japanese: "いっしょに", lesson: 9 },
  { english: "poor", japanese: "貧乏な、貧しい", lesson: 9 },
  { english: "grow", japanese: "成長する、伸びる", lesson: 9 },
  { english: "grew", japanese: "grow (成長する)の過去形", lesson: 9 },
  { english: "grow into …", japanese: "成長して…になる", lesson: 9 },
  { english: "moon", japanese: "(天体の)月", lesson: 9 },
  { english: "cry", japanese: "(声をあげて)泣く", lesson: 9 },
  { english: "be from", japanese: "〜出身である、〜起源である", lesson: 9 },
  { english: "soon", japanese: "もうすぐ、まもなく", lesson: 9 },
  { english: "full", japanese: "いっぱいの、満ちた", lesson: 9 },
  { english: "Lord Thunder", japanese: "かみなりさま", lesson: 9 },
  { english: "island", japanese: "島", lesson: 9 },
  { english: "sun", japanese: "太陽", lesson: 9 },
  { english: "bright", japanese: "ぴかぴか光る、輝く", lesson: 9 },
  { english: "rain", japanese: "(季節・時などが)めぐって来る、やって来る", lesson: 9 },
  { english: "field", japanese: "農地、牧草地、野原", lesson: 9 },
  { english: "dry", japanese: "乾いた、乾燥した", lesson: 9 },
  { english: "crop", japanese: "農作物、作物", lesson: 9 },
  { english: "young", japanese: "若い、幼い", lesson: 9 },
  { english: "wise", japanese: "賢い、賢明な、分別のある", lesson: 9 },
  { english: "wake", japanese: "目をさます、目をさまさせる", lesson: 9 },
  { english: "wake up …", japanese: "…を起こす", lesson: 9 },
  { english: "thunder", japanese: "雷、雷鳴", lesson: 9 },
  { english: "sleep", japanese: "眠る、睡眠をとる", lesson: 9 },
  { english: "noise", japanese: "物音、騒音", lesson: 9 },
  { english: "and", japanese: "(命令文などのあとで)そうすれば", lesson: 9 },
  { english: "he'll", japanese: "he willの短縮形", lesson: 9 },
  { english: "large", japanese: "大きい、広い、大規模な", lesson: 9 },
  { english: "stone", japanese: "石、小石", lesson: 9 },
  { english: "push", japanese: "押す", lesson: 9 },
  { english: "roll", japanese: "ころがる、ころがっていく", lesson: 9 },
  { english: "ready", japanese: "用意ができて、準備ができて", lesson: 9 },
  { english: "rumble", japanese: "ゴロゴロと進む、ゴロゴロ鳴る", lesson: 9 },
  { english: "down", japanese: "…の下に[へ]、…を下って、…を降りて", lesson: 9 },
  { english: "woke", japanese: "wake (目をさます)の過去形・過去分詞", lesson: 9 },
  { english: "happen", japanese: "起こる、生じる", lesson: 9 },
  { english: "job", japanese: "仕事、務め", lesson: 9 },
  { english: "beat", japanese: "(連続的に)打つ、たたく、打ちつける", lesson: 9 },
  { english: "cloud", japanese: "雲", lesson: 9 },
  { english: "cover", japanese: "おおう", lesson: 9 },
  { english: "sky", japanese: "空", lesson: 9 },
  { english: "lightning", japanese: "いなずま、電光", lesson: 9 },
  { english: "light", japanese: "明るくする、照らす", lesson: 9 },
  { english: "lit", japanese: "light (明るくする)の過去形・過去分詞", lesson: 9 },
  { english: "light up", japanese: "〜を照らす、明るくする", lesson: 9 },
  { english: "boom", japanese: "とどろき、ブーンという音", lesson: 9 },
  { english: "work", japanese: "(機械などが調子よく)動く、(計画などが)うまくいく", lesson: 9 },
  { english: "celebrate", japanese: "祝う", lesson: 9 }
];