const vocabulary3 = [
  { english: "at", japanese: "～で", lesson:1 },
  { english: "but", japanese: "しかし", lesson: 1 },
  { english: "or", japanese: "そうしなければ", lesson: 1 },
  { english: "can", japanese: "～できる", lesson: 1 },
  { english: "if", japanese: "もし～ならば", lesson: 1 },
  { english: "would", japanese: "だろうに", lesson: 1 },
  { english: "make", japanese: "を～の状態にする", lesson: 1 },
  { english: "year", japanese: "年", lesson: 1 },
  { english: "when", japanese: "～するとき", lesson: 1 },
  { english: "out", japanese: "外に", lesson: 1 },
  { english: "into", japanese: "～の中へ", lesson: 1 },
  { english: "just", japanese: "たった今", lesson: 1 },
  { english: "could", japanese: "できた", lesson: 1 },
  { english: "then", japanese: "そのとき", lesson: 1 },
  { english: "more", japanese: "もっと", lesson: 1 },
  { english: "first", japanese: "はじめて", lesson: 1 },
  { english: "because", japanese: "なぜなら", lesson: 1 },
  { english: "use", japanese: "使う", lesson: 1 },
  { english: "many", japanese: "多くの", lesson: 1 },
  { english: "those", japanese: "あれらの", lesson: 1 },
  { english: "even", japanese: "～さえ", lesson: 1 },
  { english: "back", japanese: "裏の", lesson: 1 },
  { english: "any", japanese: "どれもない", lesson: 1 },
  { english: "through", japanese: "を通り抜けて", lesson: 1 },
  { english: "after", japanese: "～の後で", lesson: 1 },
  { english: "over", japanese: "の向こう側に", lesson: 1 },
  { english: "still", japanese: "まだ", lesson: 1 },
  { english: "last", japanese: "最後の", lesson: 1 },
  { english: "never", japanese: "決してない", lesson: 1 },
  { english: "become", japanese: "になった", lesson: 1 },
  { english: "between", japanese: "～と～の間", lesson: 1 },
  { english: "most", japanese: "たいていの", lesson: 1 },
  { english: "another", japanese: "もう一つの", lesson: 1 },
  { english: "leave", japanese: "を置いていく", lesson: 1 },
  { english: "while", japanese: "しばらくの間", lesson: 1 },
  { english: "keep", japanese: "を保つ", lesson: 1 },
  { english: "let", japanese: "～に～をさせる", lesson: 1 },
  { english: "same", japanese: "同じもの", lesson: 1 },
  { english: "begin", japanese: "始まる", lesson: 1 },
  { english: "seem", japanese: "～の様に見える", lesson: 1 },
  { english: "help", japanese: "手伝う", lesson: 1 },
  { english: "problem", japanese: "問題", lesson: 1 },
  { english: "every", japanese: "どれもみな", lesson: 1 },
  { english: "hand", japanese: "を手渡す", lesson: 1 },
  { english: "right", japanese: "権利", lesson: 1 },
  { english: "hear", japanese: "を聞く", lesson: 1 },
  { english: "during", japanese: "～の間", lesson: 1 },
  { english: "play", japanese: "劇", lesson: 1 },
  { english: "government", japanese: "政府", lesson: 1 },
  { english: "run", japanese: "を主催する", lesson: 1 },
  { english: "number", japanese: "番号", lesson: 1 },
  { english: "move", japanese: "動く", lesson: 1 },
  { english: "point", japanese: "特徴", lesson: 1 },
  { english: "believe", japanese: "信じる", lesson: 1 },
  { english: "large", japanese: "大きい", lesson: 1 },
  { english: "national", japanese: "国家の", lesson: 1 },
  { english: "fact", japanese: "事実", lesson: 1 },
  { english: "study", japanese: "研究", lesson: 1 },
  { english: "though", japanese: "だけれども", lesson: 1 },
  { english: "side", japanese: "側", lesson: 1 },
  { english: "long", japanese: "長い", lesson: 1 },
  { english: "little", japanese: "小さい", lesson: 1 },
  { english: "since", japanese: "～以来", lesson: 1 },
  { english: "around", japanese: "のまわりに", lesson: 1 },
  { english: "away", japanese: "離れて", lesson: 1 },
  { english: "until", japanese: "まで", lesson: 1 },
  { english: "yet", japanese: "もう", lesson: 1 },
  { english: "line", japanese: "行", lesson: 1 },
  { english: "ever", japanese: "今まで", lesson: 1 },
  { english: "stand", japanese: "をがまんする", lesson: 1 },
  { english: "however", japanese: "しかし", lesson: 1 },
  { english: "law", japanese: "法律", lesson: 1 },
  { english: "almost", japanese: "ほとんど", lesson: 1 },
  { english: "include", japanese: "を含む", lesson: 1 },
  { english: "continue", japanese: "続く", lesson: 1 },
  { english: "once", japanese: "かつて", lesson: 1 },
  { english: "president", japanese: "大統領", lesson: 1 },
  { english: "real", japanese: "本当の", lesson: 1 },
  { english: "change", japanese: "変化", lesson: 1 },
  { english: "lead", japanese: "を導く", lesson: 1 },
  { english: "stop", japanese: "とまる", lesson: 1 },
  { english: "already", japanese: "すでに", lesson: 1 },
  { english: "health", japanese: "健康", lesson: 1 },
  { english: "person", japanese: "人", lesson: 1 },
  { english: "war", japanese: "戦争", lesson: 1 },
  { english: "grow", japanese: "成長する", lesson: 1 },
  { english: "reason", japanese: "理由", lesson: 1 },
  { english: "himself", japanese: "彼自身を", lesson: 1 },
  { english: "although", japanese: "であるけれど", lesson: 1 },
  { english: "second", japanese: "秒", lesson: 1 },
  { english: "actually", japanese: "実は", lesson: 1 },
  { english: "probably", japanese: "多分", lesson: 1 },
  { english: "human", japanese: "人間の", lesson: 1 },
  { english: "die", japanese: "死ぬ", lesson: 1 },
  { english: "stay", japanese: "滞在", lesson: 1 },
  { english: "fall", japanese: "落ちる", lesson: 1 },
  { english: "cut", japanese: "を切る", lesson: 1 },
  { english: "college", japanese: "大学", lesson: 1 },
  { english: "interest", japanese: "興味", lesson: 1 },
  { english: "death", japanese: "死", lesson:1 },
  { english: "course", japanese: "進路", lesson:2 },
  { english: "someone", japanese: "だれか", lesson:2 },
  { english: "reach", japanese: "に着く", lesson:2 },
  { english: "class", japanese: "授業", lesson:2 },
  { english: "control", japanese: "を管理する", lesson:2 },
  { english: "raise", japanese: "手などを挙げる", lesson:2 },
  { english: "perhaps", japanese: "多分", lesson:2 },
  { english: "hard", japanese: "一生懸命に", lesson:2 },
  { english: "else", japanese: "その他に", lesson:2 },
  { english: "development", japanese: "開発", lesson:2 },
  { english: "themselves", japanese: "彼ら自身", lesson:2 },
  { english: "report", japanese: "報告", lesson:2 },
  { english: "possible", japanese: "可能な", lesson:2 },
  { english: "whole", japanese: "すべての", lesson:2 },
  { english: "mind", japanese: "精神", lesson:2 },
  { english: "finally", japanese: "ついに", lesson:2 },
  { english: "less", japanese: "もっと少なく", lesson:2 },
  { english: "decision", japanese: "決定", lesson:2 },
  { english: "explain", japanese: "説明する", lesson:2 },
  { english: "son", japanese: "息子", lesson:2 },
  { english: "road", japanese: "道路", lesson:2 },
  { english: "drive", japanese: "運転する", lesson:2 },
  { english: "arm", japanese: "腕", lesson:2 },
  { english: "break", japanese: "壊れる", lesson:2 },
  { english: "difference", japanese: "ちがい", lesson:2 },
  { english: "receive", japanese: "を受け取る", lesson:2 },
  { english: "international", japanese: "国際的な", lesson:2 },
  { english: "building", japanese: "建物", lesson:2 },
  { english: "tax", japanese: "税", lesson:2 },
  { english: "agree", japanese: "賛成する", lesson:2 },
  { english: "wear", japanese: "を着ている", lesson:2 },
  { english: "support", japanese: "を支援する", lesson:2 },
  { english: "event", japanese: "行事", lesson:2 },
  { english: "matter", japanese: "問題", lesson:2 },
  { english: "site", japanese: "場所", lesson:2 },
  { english: "hit", japanese: "打つ", lesson:2 },
  { english: "oil", japanese: "油", lesson:2 },
  { english: "image", japanese: "画像", lesson:2 },
  { english: "cover", japanese: "覆う", lesson:2 },
  { english: "quite", japanese: "かなり", lesson:2 },
  { english: "certain", japanese: "確かな", lesson:2 },
  { english: "personal", japanese: "個人の", lesson:2 },
  { english: "third", japanese: "3番目", lesson:2 },
  { english: "step", japanese: "足元", lesson:2 },
  { english: "film", japanese: "映画", lesson:2 },
  { english: "choose", japanese: "選ぶ", lesson:2 },
  { english: "century", japanese: "世紀", lesson:2 },
  { english: "billion", japanese: "10億", lesson:2 },
  { english: "period", japanese: "時代", lesson:2 },
  { english: "realize", japanese: "実現する", lesson:2 },
  { english: "plant", japanese: "植物", lesson:2 },
  { english: "condition", japanese: "状況", lesson:2 },
  { english: "rule", japanese: "支配", lesson:2 },
  { english: "daughter", japanese: "娘", lesson:2 },
  { english: "husband", japanese: "夫", lesson:2 },
  { english: "close", japanese: "を閉じる", lesson:2 },
  { english: "fire", japanese: "火事", lesson:2 },
  { english: "wrong", japanese: "間違った", lesson:2 },
  { english: "increase", japanese: "を増やす", lesson:2 },
  { english: "certainly", japanese: "確かに", lesson:2 },
  { english: "rest", japanese: "休む", lesson:2 },
  { english: "behavior", japanese: "ふるまい", lesson:2 },
  { english: "fight", japanese: "たたかう", lesson:2 },
  { english: "quickly", japanese: "素早く", lesson:2 },
  { english: "order", japanese: "注文する", lesson:2 },
  { english: "fill", japanese: "いっぱいにする", lesson:2 },
  { english: "focus", japanese: "集中する", lesson:2 },
  { english: "drop", japanese: "落ちる", lesson:2 },
  { english: "blood", japanese: "血", lesson:2 },
  { english: "recently", japanese: "最近", lesson:2 },
  { english: "store", japanese: "を蓄える", lesson:2 },
  { english: "note", japanese: "紙幣", lesson:2 },
  { english: "movement", japanese: "運動", lesson:2 },
  { english: "common", japanese: "共通の", lesson:2 },
  { english: "natural", japanese: "自然の", lesson:2 },
  { english: "race", japanese: "競走", lesson:2 },
  { english: "dead", japanese: "死んだ", lesson:2 },
  { english: "shoot", japanese: "撃つ", lesson:2 },
  { english: "save", japanese: "を救う", lesson:2 },
  { english: "central", japanese: "中心の", lesson:2 },
  { english: "beyond", japanese: "をこえたところに", lesson:2 },
  { english: "protect", japanese: "を守る", lesson:2 },
  { english: "lie", japanese: "横たわる", lesson:2 },
  { english: "sign", japanese: "合図", lesson:2 },
  { english: "thought", japanese: "考え", lesson:2 },
  { english: "list", japanese: "表", lesson:2 },
  { english: "simple", japanese: "単純な", lesson:2 },
  { english: "accept", japanese: "を受け入れる", lesson:2 },
  { english: "answer", japanese: "答え", lesson:2 },
  { english: "resource", japanese: "資源", lesson:2 },
  { english: "disease", japanese: "病気", lesson:2 },
  { english: "amount", japanese: "量", lesson:2 },
  { english: "growth", japanese: "増加", lesson:2 },
  { english: "loss", japanese: "失うこと", lesson:2 },
  { english: "wonder", japanese: "不思議に思う", lesson:2 },
  { english: "pretty", japanese: "かわいい", lesson:2 },
  { english: "trade", japanese: "貿易", lesson:2 },
  { english: "probably", japanese: "多分", lesson:2 },
  { english: "outside", japanese: "の外側に", lesson:2 },
  { english: "lawyer", japanese: "弁護士", lesson:2 },
  { english: "design", japanese: "を設計する", lesson:3 },
  { english: "sort", japanese: "種類", lesson:3 },
  { english: "discuss", japanese: "話し合う", lesson:3 },
  { english: "indeed", japanese: "実に", lesson:3 },
  { english: "environment", japanese: "環境", lesson:3 },
  { english: "final", japanese: "最後の", lesson:3 },
  { english: "above", japanese: "上に", lesson:3 },
  { english: "establish", japanese: "を設立する", lesson:3 },
  { english: "imagine", japanese: "を想像する", lesson:3 },
  { english: "tonight", japanese: "今夜は", lesson:3 },
  { english: "charge", japanese: "を充電する", lesson:3 },
  { english: "weapon", japanese: "武器", lesson:3 },
  { english: "employee", japanese: "従業員", lesson:3 },
  { english: "peace", japanese: "平和", lesson:3 },
  { english: "pain", japanese: "痛み", lesson:3 },
  { english: "apply", japanese: "当てはまる", lesson:3 },
  { english: "wide", japanese: "幅の広い", lesson:3 },
  { english: "shake", japanese: "震える", lesson:3 },
  { english: "fly", japanese: "飛ぶ", lesson:3 },
  { english: "bit", japanese: "少し", lesson:3 },
  { english: "suddenly", japanese: "突然に", lesson:3 },
  { english: "discover", japanese: "を発見する", lesson:3 },
  { english: "affect", japanese: "に影響を与える", lesson:3 },
  { english: "necessary", japanese: "必要な", lesson:3 },
  { english: "instead", japanese: "そのかわりに", lesson:3 },
  { english: "case", japanese: "事例", lesson:3 },
  { english: "China", japanese: "中国", lesson:3 },
  { english: "How much ?", japanese: "どれくらいの量？", lesson:3 },
  { english: "magazine", japanese: "雑誌", lesson:3 },
  { english: "heat", japanese: "熱", lesson:3 },
  { english: "tough", japanese: "困難な", lesson:3 },
  { english: "gas", japanese: "ガソリン", lesson:3 },
  { english: "ahead", japanese: "前方に", lesson:3 },
  { english: "address", japanese: "住所", lesson:3 },
  { english: "cancer", japanese: "がん", lesson:3 },
  { english: "violence", japanese: "暴力", lesson:3 },
  { english: "discussion", japanese: "討論", lesson:3 },
  { english: "modern", japanese: "現代的な", lesson:3 },
  { english: "positive", japanese: "前向きな", lesson:3 },
  { english: "consumer", japanese: "消費者", lesson:3 },
  { english: "wish", japanese: "を望む", lesson:3 },
  { english: "scientist", japanese: "科学者", lesson:3 },
  { english: "newspaper", japanese: "新聞", lesson:3 },
  { english: "audience", japanese: "聴衆", lesson:3 },
  { english: "relate", japanese: "を～に関係させる", lesson:3 },
  { english: "debate", japanese: "討論", lesson:3 },
  { english: "born", japanese: "生まれる", lesson:3 },
  { english: "senior", japanese: "年上の", lesson:3 },
  { english: "wind", japanese: "風", lesson:3 },
  { english: "fast", japanese: "速い", lesson:3 },
  { english: "successful", japanese: "成功した", lesson:3 },
  { english: "fresh", japanese: "新鮮な", lesson:3 },
  { english: "judge", japanese: "審判員", lesson:3 },
  { english: "relation", japanese: "関係", lesson:3 },
  { english: "release", japanese: "を放出する", lesson:3 },
  { english: "opinion", japanese: "意見", lesson:3 },
  { english: "corner", japanese: "角", lesson:3 },
  { english: "effective", japanese: "効果的な", lesson:3 },
  { english: "hurt", japanese: "傷つける", lesson:3 },
  { english: "species", japanese: "種", lesson:3 },
  { english: "sky", japanese: "空", lesson:3 },
  { english: "announce", japanese: "を発表する", lesson:3 },
  { english: "please", japanese: "気に入る", lesson:3 },
  { english: "attend", japanese: "に通う", lesson:3 },
  { english: "sleep", japanese: "眠る", lesson:3 },
  { english: "nuclear", japanese: "核の", lesson:3 },
  { english: "researcher", japanese: "研究者", lesson:3 },
  { english: "encourage", japanese: "を勇気づける", lesson:3 },
  { english: "brain", japanese: "頭脳", lesson:3 },
  { english: "beginning", japanese: "最初", lesson:3 },
  { english: "Chinese", japanese: "中国語", lesson:3 },
  { english: "introduce", japanese: "紹介する", lesson:3 },
  { english: "driver", japanese: "運転手", lesson:3 },
  { english: "handle", japanese: "を処理する", lesson:3 },
  { english: "survey", japanese: "調査", lesson:3 },
  { english: "resident", japanese: "住民", lesson:3 },
  { english: "crowd", japanese: "群衆", lesson:3 },
  { english: "flight", japanese: "飛行", lesson:3 },
  { english: "quick", japanese: "速い", lesson:3 },
  { english: "bright", japanese: "明るい", lesson:3 },
  { english: "tiny", japanese: "小さな", lesson:3 },
  { english: "title", japanese: "題名", lesson:3 },
  { english: "marry", japanese: "結婚する", lesson:3 },
  { english: "survive", japanese: "生き残る", lesson:3 },
  { english: "border", japanese: "国境", lesson:3 },
  { english: "cry", japanese: "泣く", lesson:3 },
  { english: "worth", japanese: "の価値がある", lesson:3 },
  { english: "spread", japanese: "広がる", lesson:3 },
  { english: "cross", japanese: "を横切る", lesson:3 },
  { english: "anyway", japanese: "ともかく", lesson:3 },
  { english: "youth", japanese: "若さ", lesson:3 },
  { english: "wave", japanese: "波", lesson:3 },
  { english: "quarter", japanese: "4分の1", lesson:3 },
  { english: "twice", japanese: "2回", lesson:3 },
  { english: "blow", japanese: "吹く", lesson:3 },
  { english: "destroy", japanese: "を破壊する", lesson:3 },
  { english: "burn", japanese: "を燃やす", lesson:3 },
  { english: "grade", japanese: "等級", lesson:3 },
  { english: "clothes", japanese: "衣服", lesson:3 },
  { english: "promise", japanese: "約束", lesson:3 },
  { english: "neighbor", japanese: "隣人", lesson:4 },
  { english: "extend", japanese: "を広げる", lesson:4 },
  { english: "below", japanese: "下に", lesson:4 },
  { english: "dangerous", japanese: "危険な", lesson:4 },
  { english: "relatively", japanese: "比較的", lesson:4 },
  { english: "healthy", japanese: "健康な", lesson:4 },
  { english: "negative", japanese: "否定的な", lesson:4 },
  { english: "depend", japanese: "頼る", lesson:4 },
  { english: "contact", japanese: "と連絡をとる", lesson:4 },
  { english: "daily", japanese: "日常の", lesson:4 },
  { english: "pair", japanese: "一組", lesson:4 },
  { english: "exercise", japanese: "練習する", lesson:4 },
  { english: "supply", japanese: "供給", lesson:4 },
  { english: "tie", japanese: "ネクタイ", lesson:4 },
  { english: "circle", japanese: "を丸で囲む", lesson:4 },
  { english: "device", japanese: "装置", lesson:4 },
  { english: "progress", japanese: "進歩", lesson:4 },
  { english: "exchange", japanese: "交換", lesson:4 },
  { english: "clean", japanese: "をそうじする", lesson:4 },
  { english: "damage", japanese: "被害", lesson:4 },
  { english: "plate", japanese: "お皿", lesson:4 },
  { english: "army", japanese: "陸軍", lesson:4 },
  { english: "theater", japanese: "劇場", lesson:4 },
  { english: "domestic", japanese: "国内の", lesson:4 },
  { english: "rain", japanese: "雨", lesson:4 },
  { english: "respect", japanese: "を尊敬する", lesson:4 },
  { english: "instruction", japanese: "指示", lesson:4 },
  { english: "sweet", japanese: "易しい", lesson:4 },
  { english: "salt", japanese: "塩", lesson:4 },
  { english: "metal", japanese: "金属", lesson:4 },
  { english: "fat", japanese: "太った", lesson:4 },
  { english: "lip", japanese: "唇", lesson:4 },
  { english: "somewhere", japanese: "どこかに", lesson:4 },
  { english: "farmer", japanese: "農場主", lesson:4 },
  { english: "enemy", japanese: "敵", lesson:4 },
  { english: "surround", japanese: "を囲む", lesson:4 },
  { english: "carefully", japanese: "注意深く", lesson:4 },
  { english: "meaning", japanese: "意味", lesson:4 },
  { english: "weather", japanese: "天気", lesson:4 },
  { english: "connect", japanese: "つながる", lesson:4 },
  { english: "belong", japanese: "のものである", lesson:4 },
  { english: "somehow", japanese: "何らかの形で", lesson:4 },
  { english: "expensive", japanese: "高価な", lesson:4 },
  { english: "mark", japanese: "印", lesson:4 },
  { english: "visitor", japanese: "観光客", lesson:4 },
  { english: "angry", japanese: "怒った", lesson:4 },
  { english: "accident", japanese: "事故", lesson:4 },
  { english: "capture", japanese: "を捕まえる", lesson:4 },
  { english: "emergency", japanese: "緊急事態", lesson:4 },
  { english: "link", japanese: "接続", lesson:4 },
  { english: "root", japanese: "根", lesson:4 },
  { english: "mix", japanese: "混ぜる", lesson:4 },
  { english: "zone", japanese: "地帯", lesson:4 },
  { english: "shirt", japanese: "シャツ", lesson:4 },
  { english: "guide", japanese: "を案内する", lesson:4 },
  { english: "pursue", japanese: "を追い求める", lesson:4 },
  { english: "funny", japanese: "可笑しい", lesson:4 },
  { english: "neither", japanese: "～も～もない", lesson:4 },
  { english: "soil", japanese: "土", lesson:4 },
  { english: "crazy", japanese: "気の狂った", lesson:4 },
  { english: "branch", japanese: "枝", lesson:4 },
  { english: "solve", japanese: "を解決する", lesson:4 },
  { english: "bowl", japanese: "鉢", lesson:4 },
  { english: "forth", japanese: "前へ", lesson:4 },
  { english: "host", japanese: "主人", lesson:4 },
  { english: "hall", japanese: "廊下", lesson:4 },
  { english: "trust", japanese: "を信用する", lesson:4 },
  { english: "ocean", japanese: "大洋", lesson:4 },
  { english: "row", japanese: "こぐ", lesson:4 },
  { english: "mirror", japanese: "鏡", lesson:4 },
  { english: "secret", japanese: "秘密", lesson:4 },
  { english: "era", japanese: "時代", lesson:4 },
  { english: "fun", japanese: "面白い", lesson:4 },
  { english: "tear", japanese: "涙", lesson:4 },
  { english: "winner", japanese: "勝者", lesson:4 },
  { english: "cheap", japanese: "安い", lesson:4 },
  { english: "everywhere", japanese: "どこでも", lesson:4 },
  { english: "terrible", japanese: "ひどい", lesson:4 },
  { english: "rush", japanese: "殺到", lesson:4 },
  { english: "match", japanese: "試合", lesson:4 },
  { english: "limited", japanese: "限られた", lesson:4 },
  { english: "agree with", japanese: "に賛成する", lesson:4 },
  { english: "any", japanese: "どれもない", lesson:4 },
  { english: "check out", japanese: "を調査する", lesson:4 },
  { english: "drove", japanese: "運転した", lesson:4 },
  { english: "fond", japanese: "好きで", lesson:4 },
  { english: "get out", japanese: "外へ出る", lesson:4 },
  { english: "go back", japanese: "帰る", lesson:4 },
  { english: "waste", japanese: "ごみ", lesson:4 },
  { english: "definitely", japanese: "もちろん", lesson:4 },
  { english: "bomb", japanese: "爆弾", lesson:4 },
  { english: "engineer", japanese: "開発者", lesson:4 },
  { english: "succeed", japanese: "成功する", lesson:4 },
  { english: "sentence", japanese: "文", lesson:4 },
  { english: "creative", japanese: "創造力のある", lesson:4 },
  { english: "weak", japanese: "弱い", lesson:4 },
  { english: "illegal", japanese: "違法な", lesson:4 },
  { english: "signal", japanese: "信号", lesson:4 },
  { english: "wrap", japanese: "を包む", lesson:4 },
  { english: "musical", japanese: "音楽の", lesson:4 },
  { english: "climate", japanese: "気候", lesson:5 },
  { english: "graduate", japanese: "卒業する", lesson:5 },
  { english: "universe", japanese: "宇宙", lesson:5 },
  { english: "lucky", japanese: "幸運な", lesson:5 },
  { english: "arrest", japanese: "を逮捕する", lesson:5 },
  { english: "silent", japanese: "静かな", lesson:5 },
  { english: "bother", japanese: "面倒", lesson:5 },
  { english: "desert", japanese: "砂漠", lesson:5 },
  { english: "be ready for", japanese: "の用意ができている", lesson:5 },
  { english: "be amazed at", japanese: "に驚かされる", lesson:5 },
  { english: "print", japanese: "を印刷する", lesson:5 },
  { english: "reply", japanese: "返信する", lesson:5 },
  { english: "ordinary", japanese: "ふつうの", lesson:5 },
  { english: "iron", japanese: "鉄", lesson:5 },
  { english: "independence", japanese: "独立", lesson:5 },
  { english: "amazing", japanese: "驚くべき", lesson:5 },
  { english: "habit", japanese: "習慣", lesson:5 },
  { english: "disaster", japanese: "災害", lesson:5 },
  { english: "round", japanese: "まわりに", lesson:5 },
  { english: "holy", japanese: "神聖な", lesson:5 },
  { english: "smell", japanese: "においがする", lesson:5 },
  { english: "exception", japanese: "例外", lesson:5 },
  { english: "electronic", japanese: "電子の", lesson:5 },
  { english: "surely", japanese: "確かに", lesson:5 },
  { english: "smoke", japanese: "煙", lesson:5 },
  { english: "toy", japanese: "おもちゃ", lesson:5 },
  { english: "silver", japanese: "銀", lesson:5 },
  { english: "inner", japanese: "内部の", lesson:5 },
  { english: "wet", japanese: "濡れている", lesson:5 },
  { english: "poem", japanese: "詩", lesson:5 },
  { english: "rapidly", japanese: "速く", lesson:5 },
  { english: "quietly", japanese: "静かに", lesson:5 },
  { english: "flat", japanese: "平らな", lesson:5 },
  { english: "chemical", japanese: "化学物質", lesson:5 },
  { english: "heaven", japanese: "天国", lesson:5 },
  { english: "super", japanese: "とても", lesson:5 },
  { english: "fence", japanese: "塀", lesson:5 },
  { english: "survival", japanese: "存続", lesson:5 },
  { english: "found", japanese: "を見つけた", lesson:5 },
  { english: "burden", japanese: "負担", lesson:5 },
  { english: "lost", japanese: "失った", lesson:5 },
  { english: "disagree", japanese: "意見が合わない", lesson:5 },
  { english: "stranger", japanese: "見知らぬ人", lesson:5 },
  { english: "cousin", japanese: "いとこ", lesson:5 },
  { english: "blind", japanese: "目の見えない", lesson:5 },
  { english: "electricity", japanese: "電力", lesson:5 },
  { english: "square", japanese: "正方形の", lesson:5 },
  { english: "gently", japanese: "やさしく", lesson:5 },
  { english: "friendly", japanese: "好意的な", lesson:5 },
  { english: "raw", japanese: "生の", lesson:5 },
  { english: "bake", japanese: "焼く", lesson:5 },
  { english: "joy", japanese: "喜び", lesson:5 },
  { english: "protest", japanese: "抗議する", lesson:5 },
  { english: "shelter", japanese: "避難所", lesson:5 },
  { english: "entrance", japanese: "入口", lesson:5 },
  { english: "net", japanese: "網", lesson:5 },
  { english: "poet", japanese: "詩人", lesson:5 },
  { english: "honey", japanese: "蜂蜜", lesson:5 },
  { english: "pale", japanese: "青ざめた", lesson:5 },
  { english: "scared", japanese: "こわがって", lesson:5 },
  { english: "not at all", japanese: "少しもない", lesson:5 },
  { english: "a kind of", japanese: "一種の", lesson:5 },
  { english: "all the time", japanese: "常に", lesson:5 },
  { english: "amaze", japanese: "をびっくりさせる", lesson:5 },
  { english: "ashamed", japanese: "恥じて", lesson:5 },
  { english: "be satisfied with", japanese: "に満足する", lesson:5 },
  { english: "beginner", japanese: "初心者", lesson:5 },
  { english: "depend on", japanese: "に頼る", lesson:5 },
  { english: "ending", japanese: "終わり", lesson:5 },
  { english: "even if", japanese: "たとえ～だとしても", lesson:5 },
  { english: "rainy", japanese: "雨の", lesson:5 },
  { english: "run out of", japanese: "を使い果たす", lesson:5 },
  { english: "shade", japanese: "陰", lesson:5 },
  { english: "custom", japanese: "習慣", lesson:5 },
  { english: "satisfy", japanese: "を満足させる", lesson:5 },
  { english: "besides", japanese: "そのうえ", lesson:5 },
  { english: "given", japanese: "与えた", lesson:5 },
  { english: "uniform", japanese: "制服", lesson:5 },
  { english: "horizon", japanese: "地平線", lesson:5 },
  { english: "curious", japanese: "好奇心の強い", lesson:5 },
  { english: "valley", japanese: "谷", lesson:5 },
  { english: "discrimination", japanese: "差別", lesson:5 },
  { english: "god", japanese: "神", lesson:5 },
  { english: "legacy", japanese: "遺産", lesson:5 },
  { english: "battery", japanese: "電池", lesson:5 },
  { english: "garage", japanese: "車庫", lesson:5 },
  { english: "weekly", japanese: "週刊の", lesson:5 },
  { english: "brush", japanese: "筆", lesson:5 },
  { english: "artistic", japanese: "芸術的な", lesson:5 },
  { english: "ban", japanese: "を禁止する", lesson:5 },
  { english: "rhythm", japanese: "リズム", lesson:5 },
  { english: "lovely", japanese: "美しい", lesson:5 },
  { english: "be different from", japanese: "とはちがっている", lesson:5 },
  { english: "painter", japanese: "画家", lesson:5 },
  { english: "courage", japanese: "勇気", lesson:5 },
  { english: "coal", japanese: "石炭", lesson:5 },
  { english: "abroad", japanese: "外国へ", lesson:5 },
  { english: "rose", japanese: "昇った", lesson:5 },
  { english: "surprisingly", japanese: "驚いたことには", lesson:5 },
  { english: "gentle", japanese: "やさしい", lesson:5 },
  { english: "invent", japanese: "を発明する", lesson:6 },
  { english: "excited", japanese: "興奮した", lesson:6 },
  { english: "pleased", japanese: "喜んで", lesson:6 },
  { english: "midnight", japanese: "真夜中", lesson:6 },
  { english: "fold", japanese: "を折る", lesson:6 },
  { english: "beef", japanese: "牛肉", lesson:6 },
  { english: "monthly", japanese: "月に1回の", lesson:6 },
  { english: "cloth", japanese: "布", lesson:6 },
  { english: "strict", japanese: "厳しい", lesson:6 },
  { english: "announcement", japanese: "発表", lesson:6 },
  { english: "uncomfortable", japanese: "心地の悪い", lesson:6 },
  { english: "radiation", japanese: "放射線", lesson:6 },
  { english: "peaceful", japanese: "平和な", lesson:6 },
  { english: "colony", japanese: "植民地", lesson:6 },
  { english: "prize", japanese: "賞", lesson:6 },
  { english: "injure", japanese: "を傷つける", lesson:6 },
  { english: "sidewalk", japanese: "歩道", lesson:6 },
  { english: "traveler", japanese: "旅行者", lesson:6 },
  { english: "statue", japanese: "像", lesson:6 },
  { english: "gym", japanese: "体育館", lesson:6 },
  { english: "lamp", japanese: "明かり", lesson:6 },
  { english: "not only but also ～", japanese: "だけでなく～もまた", lesson:6 },
  { english: "so far", japanese: "これまでは", lesson:6 },
  { english: "after a while", japanese: "しばらくして", lesson:6 },
  { english: "carbon dioxide", japanese: "二酸化炭素", lesson:6 },
  { english: "convenient", japanese: "便利な", lesson:6 },
  { english: "drop out", japanese: "中退する", lesson:6 },
  { english: "extinguisher", japanese: "消火器", lesson:6 },
  { english: "fox", japanese: "キツネ", lesson:6 },
  { english: "go on", japanese: "する", lesson:6 },
  { english: "lost", japanese: "失った", lesson:6 },
  { english: "pass by", japanese: "通り過ぎる", lesson:6 },
  { english: "sunshine", japanese: "日光", lesson:6 },
  { english: "silk", japanese: "絹", lesson:6 },
  { english: "kit", japanese: "道具一式", lesson:6 },
  { english: "import", japanese: "を輸入する", lesson:6 },
  { english: "treasure", japanese: "宝物", lesson:6 },
  { english: "donate", japanese: "を寄付する", lesson:6 },
  { english: "tightly", japanese: "しっかりと", lesson:6 },
  { english: "queen", japanese: "女王", lesson:6 },
  { english: "merchant", japanese: "商人", lesson:6 },
  { english: "steam", japanese: "蒸気", lesson:6 },
  { english: "calm", japanese: "落ちついた", lesson:6 },
  { english: "exam", japanese: "試験", lesson:6 },
  { english: "functional", japanese: "実用的な", lesson:6 },
  { english: "boil", japanese: "ゆでる", lesson:6 },
  { english: "earthquake", japanese: "地震", lesson:6 },
  { english: "pork", japanese: "豚肉", lesson:6 },
  { english: "safely", japanese: "安全に", lesson:6 },
  { english: "fortunately", japanese: "幸運にも", lesson:6 },
  { english: "elephant", japanese: "ゾウ", lesson:6 },
  { english: "be in danger of", japanese: "の危険にさらされている", lesson:6 },
  { english: "dam", japanese: "ダム", lesson:6 },
  { english: "well-known", japanese: "有名な", lesson:6 },
  { english: "pencil", japanese: "えんぴつ", lesson:6 },
  { english: "swimming", japanese: "水泳", lesson:6 },
  { english: "colorful", japanese: "色彩に富んだ", lesson:6 },
  { english: "dot", japanese: "点", lesson:6 },
  { english: "unfair", japanese: "不公平な", lesson:6 },
  { english: "feather", japanese: "羽", lesson:6 },
  { english: "ecosystem", japanese: "生態系", lesson:6 },
  { english: "transport", japanese: "を輸送する", lesson:6 },
  { english: "awake", japanese: "目が覚める", lesson:6 },
  { english: "palace", japanese: "宮殿", lesson:6 },
  { english: "happily", japanese: "幸せに", lesson:6 },
  { english: "unhappy", japanese: "不幸な", lesson:6 },
  { english: "fantastic", japanese: "素晴らしい", lesson:6 },
  { english: "policeman", japanese: "警官", lesson:6 },
  { english: "graduation", japanese: "卒業", lesson:6 },
  { english: "freely", japanese: "自由に", lesson:6 },
  { english: "arrow", japanese: "矢", lesson:6 },
  { english: "brave", japanese: "勇敢な", lesson:6 },
  { english: "sustainable", japanese: "存続可能な", lesson:6 },
  { english: "awesome", japanese: "すばらしい", lesson:6 },
  { english: "barber", japanese: "散髪屋", lesson:6 },
  { english: "breed", japanese: "を飼育する", lesson:6 },
  { english: "case", japanese: "事例", lesson:6 },
  { english: "decide to", japanese: "しようと決心する", lesson:6 },
  { english: "endangered", japanese: "絶滅の危機にさらされている", lesson:6 },
  { english: "foolish", japanese: "愚かな", lesson:6 },
  { english: "hopeful", japanese: "希望を持っている", lesson:6 },
  { english: "point", japanese: "特徴", lesson:6 },
  { english: "then", japanese: "そのとき", lesson:6 },
  { english: "not always", japanese: "いつもとは限らない", lesson:6 },
  { english: "die out", japanese: "絶滅する", lesson:6 },
  { english: "eat out", japanese: "外食する", lesson:6 },
  { english: "get over", japanese: "を乗りこえる", lesson:6 },
  { english: "go on", japanese: "する", lesson:6 },
  { english: "more than", japanese: "より多い", lesson:6 },
  { english: "parking lot", japanese: "駐車場", lesson:6 },
  { english: "third", japanese: "3番目", lesson:6 },
  { english: "calligraphy", japanese: "書道", lesson:6 },
  { english: "countryside", japanese: "田舎", lesson:6 },
  { english: "in those days", japanese: "当時は", lesson:6 },
  { english: "yet", japanese: "もう", lesson:6 },
  { english: "frog", japanese: "カエル", lesson:6 },
  { english: "violent", japanese: "暴力的な", lesson:6 },
  { english: "evacuation drill", japanese: "避難訓練", lesson:6 },
  { english: "in the open air", japanese: "屋外で", lesson:6 },
  { english: "or", japanese: "そうしなければ", lesson:6 },
  { english: "stationery", japanese: "文房具", lesson:7 },
  { english: "custom-made", japanese: "注文で作った", lesson:7 },
  { english: "electronic device", japanese: "電子機器", lesson:7 },
  { english: "fire", japanese: "火事", lesson:7 },
  { english: "in season", japanese: "旬で", lesson:7 },
  { english: "little", japanese: "小さい", lesson:7 },
  { english: "protest", japanese: "抗議する", lesson:7 },
  { english: "rainwater", japanese: "雨水", lesson:7 },
  { english: "up until", japanese: "まで", lesson:7 },
  { english: "twice", japanese: "2回", lesson:7 },
  { english: "seasonal", japanese: "季節の", lesson:7 },
  { english: "police officer", japanese: "警察官", lesson:7 },
  { english: "That's very kind of you", japanese: "親切にありがとうございます", lesson:7 },
  { english: "fourteenth", japanese: "14番目", lesson:7 },
  { english: "feel free to", japanese: "遠慮なくする", lesson:7 },
  { english: "prince", japanese: "王子", lesson:7 },
  { english: "run away", japanese: "逃げる", lesson:7 },
  { english: "sent", japanese: "送った", lesson:7 },
  { english: "on the way", japanese: "帰る途中で", lesson:7 },
  { english: "noisy", japanese: "騒がしい", lesson:7 },
  { english: "jewel", japanese: "宝石", lesson:7 },
  { english: "fossil fuel", japanese: "化石燃料", lesson:7 },
  { english: "human being", japanese: "人間", lesson:7 },
  { english: "paper crane", japanese: "折り鶴", lesson:7 },
  { english: "pal", japanese: "友だち", lesson:7 },
  { english: "so that ～", japanese: "とてもなので～だ", lesson:7 },
  { english: "nuclear power", japanese: "原子力", lesson:7 },
  { english: "relate to ～", japanese: "を～に関係させる", lesson:7 },
  { english: "encourage to ～", japanese: "に～するように促す", lesson:7 },
  { english: "make all the difference", japanese: "大きなちがいを生む", lesson:7 },
  { english: "wind power", japanese: "風力", lesson:7 },
  { english: "more and more", japanese: "ますます多くの", lesson:7 },
  { english: "would like to ～", japanese: "に～してほしい", lesson:7 },
  { english: "overseas", japanese: "外国へ", lesson:7 },
  { english: "renewable", japanese: "再生可能な", lesson:7 },
  { english: "go through", japanese: "人生を送る", lesson:7 },
  { english: "syllable", japanese: "音節", lesson:7 },
  { english: "shaking", japanese: "揺れ", lesson:7 },
  { english: "lullaby", japanese: "子守歌", lesson:7 },
  { english: "sleepy", japanese: "眠い", lesson:7 },
  { english: "evacuation", japanese: "避難", lesson:7 },
  { english: "in case of", japanese: "の場合には", lesson:7 },
  { english: "plastic bag", japanese: "ビニールぶくろ", lesson:7 },
  { english: "said", japanese: "言った", lesson:7 },
  { english: "follower", japanese: "支持者", lesson:7 },
  { english: "meant", japanese: "意味した", lesson:7 },
  { english: "populous", japanese: "人口の多い", lesson:7 },
  { english: "spelling", japanese: "綴り", lesson:7 },
  { english: "umbrella", japanese: "かさ", lesson:7 },
  { english: "won", japanese: "勝った", lesson:7 },
  { english: "this way", japanese: "このように", lesson:7 },
  { english: "heard", japanese: "聞いた", lesson:7 },
  { english: "held", japanese: "握った", lesson:7 },
  { english: "made", japanese: "作った", lesson:7 },
  { english: "yen", japanese: "円", lesson:7 },
  { english: "extinction", japanese: "絶滅", lesson:7 },
  { english: "unused", japanese: "未使用", lesson:7 },
  { english: "what to", japanese: "何をすべきか", lesson:7 },
  { english: "every year", japanese: "毎年", lesson:7 },
  { english: "railway", japanese: "鉄道", lesson:7 },
  { english: "hope to", japanese: "したいと願う", lesson:7 },
  { english: "high school", japanese: "高校", lesson:7 },
  { english: "lazy", japanese: "怠け者の", lesson:7 },
  { english: "stylish", japanese: "おしゃれな", lesson:7 },
  { english: "sold", japanese: "売った", lesson:7 },
  { english: "How long ?", japanese: "どれくらいの長さ？", lesson:7 },
  { english: "tell to ～", japanese: "に～するように言う", lesson:7 },
  { english: "latest", japanese: "最新の", lesson:7 },
  { english: "inventor", japanese: "発明家", lesson:7 },
  { english: "stand up", japanese: "立ち上がる", lesson:7 },
  { english: "sunset", japanese: "日没", lesson:7 },
  { english: "too to ～", japanese: "～するにはすぎる", lesson:7 },
  { english: "interdependent", japanese: "相互に依存している", lesson:7 },
  { english: "instead of", japanese: "のかわりに", lesson:7 },
  { english: "mini", japanese: "小型の", lesson:7 },
  { english: "grew", japanese: "育った", lesson:7 },
  { english: "prepared", japanese: "用意ができている", lesson:7 },
  { english: "delicious", japanese: "おいしい", lesson:7 },
  { english: "the globe", japanese: "地球", lesson:7 },
  { english: "mining", japanese: "採鉱", lesson:7 },
  { english: "zoo", japanese: "動物園", lesson:7 },
  { english: "human rights", japanese: "人権", lesson:7 },
  { english: "one by one", japanese: "1つずつ", lesson:7 },
  { english: "rhyme", japanese: "韻をふむ", lesson:7 },
  { english: "get fired", japanese: "解雇される", lesson:7 },
  { english: "hand out", japanese: "を配る", lesson:7 }
];
